### ISSUE TITLE
Unable to run cells in Notebook in production environment

### ISSUE THREAD

**Issue by BrandonEscamilla** [datalayer/jupyter-ui#100]
### Description:

I'm experiencing an issue where I am unable to run cells in the Notebook. It works fine on my local machine, but when I build and run it in the production environment, the issue arises. I have captured some screenshots of the console errors that occur when I try to run a simple command in the cell. Thank you in advance!

### Screenshots:

![CleanShot 2023-09-18 at 19 52 20](https://github.com/datalayer/jupyter-ui/assets/21966716/cc0deda7-c87b-456e-b9f1-21319c879e91)
![CleanShot 2023-09-18 at 19 52 10](https://github.com/datalayer/jupyter-ui/assets/21966716/71c76560-17f2-48c2-b914-99d82b395393)

### Additional Information:
- I am following the advice from previous comments to use yarn and ﻿reactStrictMode: false.
- The ﻿scheduleWork issue occurs when I click within a cell and focus.

### Production Environment Information:
	•	Deployment service: Amplify
	•	node version: 18.17.1
	•	jupyter-react version: 0.7.6
	•	next.js version: 13.4.9

**Comment by echarles** [comment]
@BrandonEscamilla I have added in the example next.js repository the option to generated a static version of the next.js app https://github.com/echarles/jupyter-nextjs-example/commit/488d008ca9a1a226048a16cc9277f11fd7f5818a

With that config, I have run `yarn build` and I have deployed the generated static site under `out`  in a HTTP server. Going with my browser to that local web server returns a working notebok that sdoes not show the error you encounter.

> Deployment service: Amplify

Can you share a bit more details on the steps you take to deploy your next.js. app?

**Comment by BrandonEscamilla** [comment]
Thank you, @echarles. As my app has been growing and I am not using server actions, I have encountered issues with the export method. I have built a production version of this app (https://github.com/echarles/jupyter-nextjs-example) using Amplify and it seems the issue persists despite it working fine in the local environment, including successful exports. I have provided the URL for you to review and help identify any missed steps. I also suspect that the Node.js version used in the app's build process might be a factor. Additionally, I have included the YAML used for the build. It is a simple configuration running ﻿yarn install and ﻿yarn run build.

![CleanShot 2023-09-19 at 13 15 53](https://github.com/datalayer/jupyter-ui/assets/21966716/7d579efa-a712-4bb4-bc4c-27785bac740e)

**Comment by echarles** [comment]
I have no experience with Amplify. Thx for sharing the link, I indeed hit the same issue with my Chrome and my Firefox. The returned issue sounds generated by the Next.js code.

If not yet done, can you confirm that your configuration is working with a simple Next.js hello world (no jupyter-react). Then if you have cycles for, it would be good to try a Jupyter React simple notebook without Next.js. Based on your findings (issue or not), we will be able to pinpoint better the root of the issue.

**Comment by echarles** [comment]
That is awesome news. Glad it is working.

@BrandonEscamilla Would you mind providing the needed steps to run with Amplify. I would take them in the docs. Or if you feel the mood, you could even open PR to update the docs (you can just add a mardown in https://github.com/datalayer/jupyter-ui/tree/main/docs/docs)

**Comment by BrandonEscamilla** [comment]
Hey @echarles, sure thing! where exactly in the docs (deployment?) should I include these steps?

**Comment by echarles** [comment]
> Hey @echarles, sure thing! where exactly in the docs (deployment?) should I include these steps?

Thx, the deployment section would be a great place indeed.
