### ISSUE TITLE
Potential breaking change in 0.7.7

### ISSUE THREAD

**Issue by BrandonEscamilla** [datalayer/jupyter-ui#105]
Hi @echarles,

After upgrading to version 0.7.7, it appears that there is an issue where the URL from the Jupyter context is not being used and it defaults to the localhost URL. Wondering if there is any specific change in the way to define server URLs. Thanks in advance!

![CleanShot 2023-09-26 at 15 03 19](https://github.com/datalayer/jupyter-ui/assets/21966716/d8eb3bd3-07d8-4932-80fc-e57599907297)

**Comment by echarles** [comment]
That was a regression I have seen after release. I should be fixed in main branch. Let me push a release tomorrow so you can confirm it is fixed. Thx!

**Comment by echarles** [comment]
@BrandonEscamilla Just released `0.7.8` which should fix that issue.

**Comment by BrandonEscamilla** [comment]
Just tested, it works as expected thanks!
