### ISSUE TITLE
Error when saving file from a jupyter server docker

### ISSUE THREAD

**Issue by kennyster92** [datalayer/jupyter-ui#108]
Hi all!

I developed a docker which is responsible to run a jupyter server in it. I basically share a folder and define a port where to listen for the jupyter server.

Then in the frontend I configure properly the urls and token and I am able to see the Notebook in the frontend.
The problem appears when I try to save the Notebook's file. Indeed when I try to save it from the jupyter server running on a docker I get the message `File Save Erro for file.ipynb Unexpected error while saving file: file.ipynb 'coroutine' object is not subscriptable`.

This does not appear if I start the jupyter server from command line with the same configuration file and properly port and folder settings.

Am I missing a necessary package which is needed? 

Many thanks

**Comment by echarles** [comment]
>  I basically share a folder

Can you confirm the folder you share has write access? You can double check that if your docker has jupyterlab installed (if not, add pip install jupyterlab) and use the default jupyterlab to try reading/writing a notebook

>  File Save Erro for file.ipynb Unexpected error while saving file: file.ipynb 'coroutine' object is not subscriptable.

The full stacktrace would be usefull.

**Comment by kennyster92** [comment]
Thank you for the suggestion. I tried to give permission and nothing seems to be changed.

I paste here the stacktrace of the docker.

> [I 2023-10-24 12:04:41.903 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
> [W 2023-10-24 12:04:56.185 ServerApp] Clearing invalid/expired login cookie username-localhost-8686
> /opt/conda/lib/python3.8/site-packages/jupytext/contentsmanager.py:194: RuntimeWarning: coroutine 'AsyncFileContentsManager.file_exists' was never awaited
>   if (
> RuntimeWarning: Enable tracemalloc to get the object allocation traceback
> /opt/conda/lib/python3.8/site-packages/jupytext/contentsmanager.py:194: RuntimeWarning: coroutine 'AsyncFileContentsManager.dir_exists' was never awaited
>   if (
> RuntimeWarning: Enable tracemalloc to get the object allocation traceback
> [I 2023-10-24 12:05:00.000 ServerApp] Kernel started: 4576817a-6829-483b-acff-f89119e17e36
> [I 2023-10-24 12:05:00.686 ServerApp] Connecting to kernel 4576817a-6829-483b-acff-f89119e17e36.
> /opt/conda/lib/python3.8/site-packages/jupytext/contentsmanager.py:194: RuntimeWarning: coroutine 'AsyncFileContentsManager.file_exists' was never awaited
>   if (
> RuntimeWarning: Enable tracemalloc to get the object allocation traceback
> /opt/conda/lib/python3.8/site-packages/jupytext/contentsmanager.py:194: RuntimeWarning: coroutine 'AsyncFileContentsManager.dir_exists' was never awaited
>   if (
> RuntimeWarning: Enable tracemalloc to get the object allocation traceback
> [I 2023-10-24 12:05:00.792 ServerApp] Writing notebook-signing key to /root/.local/share/jupyter/notebook_secret
> [W 2023-10-24 12:05:00.795 ServerApp] Notebook test.ipynb is not trusted

**Comment by echarles** [comment]
@kennyster92 It is hard to say something from the details you shared. Can you install jupyterlab in your docker and confirm that the default jupyterlab is working fine?

**Comment by kennyster92** [comment]
I tried to install and run jupyterlab but in my docker is not working, so probably I am missing something. Running an official jupyterlab image it works. I will investigate more on it, for now thank you for the help!

**Comment by kennyster92** [comment]
I solved the issue using a server docker from the image provided by Jupyter [jupyter/datascience-notebook](https://hub.docker.com/r/jupyter/datascience-notebook).

Thank you for the help

**Comment by echarles** [comment]
Great. Can this issue be closed?

**Comment by kennyster92** [comment]
yes thank you
