### ISSUE TITLE
Custom Jupyter Server

### ISSUE THREAD

**Issue by alishobeiri** [datalayer/jupyter-ui#111]
Hi, 

Thanks so much for the library, this looks really cool and I'm excited to start working with it!

I am currently struggling to use the components with a custom Jupyter Server. I have already reviewed https://github.com/datalayer/jupyter-ui/issues/83 and was still not able to fix the issue I was running into.

Here is the steps I have tried so far:
1. Install Jupyter Server, Lab
2. Create a `~/.jupyter/jupyter_notebook_config.py` with the following contents:
```
c.ServerApp.ip = '0.0.0.0'
c.ServerApp.port = 8686
c.ServerApp.port_retries = 0

c.ServerApp.disable_check_xsrf = True
ORIGIN = 'http://localhost:3000'
c.ServerApp.allow_origin = ORIGIN # Best to restrict the ORIGIN
c.ServerApp.allow_origin_pat = '.*'
c.ServerApp.allow_credentials = True
c.ServerApp.tornado_settings = {
  'headers': {
   'Access-Control-Allow-Origin': ORIGIN,  # Best to restrict the ORIGIN
    'Access-Control-Allow-Methods': '*',
    'Access-Control-Allow-Headers': 'Accept, Accept-Encoding, Accept-Language, Authorization, Cache-Control, Connection, Content-Type, Host, Origin, Pragma, Referer, sec-ch-ua, sec-ch-ua-mobile, sec-ch-ua-platform, Sec-Fetch-Dest, Sec-Fetch-Mode, Sec-Fetch-Site, Upgrade, User-Agent, X-XSRFToken, X-Datalayer, Expires',
    'Access-Control-Allow-Credentials': 'true',
    'Content-Security-Policy': f"frame-ancestors 'self' {ORIGIN} ",
  },
  'cookie_options': {
    'SameSite': 'None',
    'Secure': True
  }
}
c.IdentityProvider.cookie_options = {
  "SameSite": "None",
  "Secure": True,
}

c.ServerApp.jpserver_extensions = {
    'jupyterlab': True,
    'jupyter_server_terminals': True,
}

content_dir = os.path.dirname(os.path.realpath(__file__))
c.ServerApp.root_dir = content_dir
c.ServerApp.preferred_dir = content_dir

c.ServerApp.base_url = '/api/jupyter'
c.ServerApp.default_url = '/api/jupyter/lab'
```

3. Change the notebook component to point to the following:
```
      <Jupyter
        jupyterServerHttpUrl="http://localhost:8686/api/jupyter"
        jupyterServerWsUrl="ws://localhost:8686/api/jupyter"
        jupyterToken="1e208f7413080fd4a739ee5b815d061d59ac23f7bf80d035"
      >
        <Notebook
          path="ipywidgets.ipynb"
          uid="notebook-nextjs-1"
          externalIPyWidgets={[
            { name: "@widgetti/jupyter-react", version: "0.3.0" },
            { name: "bqplot", version: "0.5.42" },
            { name: "jupyter-matplotlib", version: "0.11.3" },
          ]}
          cellSidebarMargin={120}
          CellSidebar={CellSidebar}
        />
    </Jupyter>
```

4. Run `jupyter lab  --debug --config=~/.jupyter/jupyter_notebook_config.py` and `npm run dev` to start the NextJS server

The login works correctly, but then I start to see the following:
```
[W 2023-11-14 09:19:13.224 ServerApp] 403 GET /api/jupyter/api/events/subscribe?token=[secret] (@127.0.0.1) 2.27ms referer=None
[W 2023-11-14 09:19:14.906 ServerApp] Couldn't authenticate WebSocket connection
[D 2023-11-14 09:19:14.907 ServerApp] Using contents: services/contents
[D 2023-11-14 09:19:14.908 ServerApp] Using contents: services/contents
[W 2023-11-14 09:19:14.909 ServerApp] 403 GET /api/jupyter/api/events/subscribe?token=[secret] (@127.0.0.1) 3.60ms referer=None
[D 2023-11-14 09:19:16.814 ServerApp] 200 OPTIONS /api/jupyter/api/sessions (@127.0.0.1) 1.30ms
[W 2023-11-14 09:19:16.816 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/Users/alishobeiri/src/vizly-server/backend/api/venv/lib/python3.9/site-packages/tornado/web.py", line 1784, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/Users/alishobeiri/src/vizly-server/backend/api/venv/lib/python3.9/site-packages/tornado/web.py", line 3278, in wrapper
        url = self.get_login_url()
      File "/Users/alishobeiri/src/vizly-server/backend/api/venv/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 761, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
```

Any idea what I might be doing wrong here or what I could look to try?

**Comment by echarles** [comment]
Hi @alishobeiri Thx a lot for trying out and reporting question. To validate your jupyter config, could you point your browser directly to `http://localhost:8686/api/jupyter` and use the token you have defined `1e208f7413080fd4a739ee5b815d061d59ac23f7bf80d035`.

I don't see any token defined in your `~/.jupyter/jupyter_notebook_config.py` file, so you may need to add `c.IdentityProvider.token = '1e208f7413080fd4a739ee5b815d061d59ac23f7bf80d035'` in that file.

**Comment by alishobeiri** [comment]
Hi Eric, 

Thanks so much for the reply, I realized that I had a token mismatch and I believe that is what was causing the problem as you mentioned. I just realized it as you replied. The components are rendering now, and I am just working on being able to actually execute the code using my Jupyter Server. When I press the `Run Code` button nothing seems to happen, but I assume I probably need to mess with my configuration to get that to work. 

I am seeing the following errors, if you might have any thoughts:
![image](https://github.com/datalayer/jupyter-ui/assets/18422723/94ca2960-1699-41e6-9098-c551161a4073)

Thanks again for all your help!

**Comment by echarles** [comment]
The errors you see in the devtools are prolly not the cause of the `Run Code` not working.  I remember having encountered one day that issue, but can not remember what was the cause... Any other error in the devtool when you click on run? Does `http://localhost:8686/api/jupyter/ipywidgets.ipynb` works fine? Otherwise, maybe start without the ipywidgets props? Also are you using the latest version?

**Comment by alishobeiri** [comment]
Thanks again for your time and reply. 

This is the version I am using, which I believe is the latest:
```
"@datalayer/jupyter-react": "0.8.0",
```

I commented out the ipywidgets as well, and that did not resolve the issue:
```
    <>
      <Jupyter
        jupyterServerHttpUrl="http://localhost:8686/api/jupyter"
        jupyterServerWsUrl="ws://localhost:8686/api/jupyter"
        jupyterToken="60c1661cc408f978c309d04157af55c9588ff9557c9380e4fb50785750703da6"
      >
        <Notebook
          path="Untitled.ipynb"
          uid="notebook-nextjs-1"
          // externalIPyWidgets={[
          //   { name: "@widgetti/jupyter-react", version: "0.3.0" },
          //   { name: "bqplot", version: "0.5.42" },
          //   { name: "jupyter-matplotlib", version: "0.11.3" },
          // ]}
          cellSidebarMargin={120}
          CellSidebar={CellSidebar}
        />
    </Jupyter>
  </>
```

When I click run, I don't see any errors or anything in network tab or console. 

When I go to `http://localhost:8686/api/jupyter/Untitled.ipynb` I get a 404 error, but when I go to `http://localhost:8686/api/jupyter/lab/tree/Untitled.ipynb` I am able to edit the notebook

**Comment by alishobeiri** [comment]
So when I access the Notebook through `http://localhost:8686/api/jupyter/lab/tree/Untitled.ipynb` I am able to edit the Notebook and produce outputs using both Shift + Enter and the run button. 

In my NextJS app, when I refresh the page, the changes I make to the Notebook are reflected in the datalayer/juypter-ui react components as well. 

Jupyter Lab:
<img width="2550" alt="image" src="https://github.com/datalayer/jupyter-ui/assets/18422723/e033ff72-d926-4f17-bf87-907957810752">

NextJS:
<img width="1717" alt="image" src="https://github.com/datalayer/jupyter-ui/assets/18422723/85452366-e87c-465a-8b36-bbba9d5303dc">


This is the Jupyter related information when I run `pip freeze` in case that might be relevant as well:
```
jupyter==1.0.0
jupyter-console==6.6.3
jupyter-events==0.9.0
jupyter-lsp==2.2.0
jupyter_client==8.6.0
jupyter_core==5.5.0
jupyter_server==2.10.0
jupyter_server_terminals==0.4.4
jupyterlab==4.0.8
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.9
jupyterlab_server==2.25.1
```

**Comment by alishobeiri** [comment]
This is the Jupyter Lab logs as well (in debug mode) when I refresh the NextJS application and try to run the code: 
[jupyter_lab_logs.txt](https://github.com/datalayer/jupyter-ui/files/13353614/jupyter_lab_logs.txt)

**Comment by alishobeiri** [comment]
Here are the logs from when I run the `jupyter lab --debug --config=~/.jupyter/jupyter_notebook_config.py` command, connect to the NextJS application and then try to run a cell both through the `Run` button and the `Shift+Enter` method:
[jupyter_lab_logs.txt](https://github.com/datalayer/jupyter-ui/files/13353676/jupyter_lab_logs.txt)

**Comment by echarles** [comment]
Thx for the 2 logs. I have looked at it but don't see any issue. I have upgrade my next-js example repo to jupyter-react 0.8.0 https://github.com/echarles/jupyter-nextjs-example/commit/b891eb3df73a6944c06b6ba84b3be1a4ee261328 and confirms that the run works fine (shift-enter).

To know if this is a server issue, you could change your code and point to the oss servers

```ts
      <Jupyter
        jupyterServerHttpUrl="https://oss.datalayer.tech/api/jupyter"
        jupyterServerWsUrl="wss://oss.datalayer.tech/api/jupyter"
        jupyterToken="60c1661cc408f978c309d04157af55c9588ff9557c9380e4fb50785750703da6"
      >

```

**Comment by alishobeiri** [comment]
Thanks so much for testing that, I just tried running a clean install of the latest nextjs application and the previous version and I was not able to run code on either of them. 

I actually tried making my own server because I thought the hosted server doesn't allow code execution :D 

I also tried disabling my Ad Blocker in case maybe that was causing the issue. 

Here are some environment factors in case that might have an effect:
```
node --version
v18.18.1
```

```
npm -v
10.2.0
```

I tried to use `yarn` but I wasn't able to due to a version mismatch, but here is my `yarn` version:
```
yarn --version
1.22.20
```

Could the issue be that I am using `npm` instead of `yarn`?

**Comment by echarles** [comment]
yarn 1 will not work, you need yarn 3. Can you try pointing to the hosted server and confirm it is working (or not)? Thx.

**Comment by alishobeiri** [comment]
I'm really sorry, I just tried it with `yarn` and it works with the hosted server, thanks so much for all your help. My apologies for wasting your time. 

I always thought `yarn` and `npm` were the same and was just a matter of personal preference but I guess I have a lot to learn! Thank you again for all your help :)

**Comment by echarles** [comment]
That is so coool 👍 Yarn is indeed different from npm. We have to use yarn because it is a downstream jupyterlab requirement. This may evolve to support npm, but for now, this is what it is. Maybe now you can try with you local server?

**Comment by alishobeiri** [comment]
Had to mess around with some `yarn` dependencies that's why it took me a little bit, but it is working now!

Thanks a lot again for all your help 😄

**Comment by echarles** [comment]
Closing as resolved.
