### ISSUE TITLE
Ipywidgets : Widget Value Not Updating in Subsequent Cells

### ISSUE THREAD

**Issue by alainlep** [datalayer/jupyter-ui#128]
## Description

Hi, 

I've encountered a problem with ipywidgets, specifically after upgrading to version 0.8.0. In previous versions, changing the value of a slider widget in one Jupyter notebook cell would correctly update and reflect in subsequent cells when accessed. However, post-upgrade, this expected behavior no longer occurs.

<img width="951" alt="image" src="https://github.com/datalayer/jupyter-ui/assets/17934185/f5fd1d59-0c32-46ab-ba80-31ddbc1b5d6e">

## Reproduce

1. Create a Jupyter notebook with two cells.
2. In the first cell:
- Import ipywidgets and IPython.display.
- Create an IntSlider widget with initial value 50, min 0, max 100, and step 1.
- Display the slider using display().
3. In the second cell:
- Access the slider's value.
- Print the slider value.
4. Change the slider's value in the first cell.
5. Run the second cell to print the slider value.

## Expected behavior

The second cell should print the updated slider value after changing it in the first cell and then running the second cell.

## Context

- Datalayer version: 0.8.0
- Operating System and version: Ubuntu 20.04.6 LTS
- Browser and version: Microsoft Edge Version 120.0.2210.61 (Version officielle) (64 bits)

- <details><summary>Browser Output</summary>
  - I also saw this in the console, it may be related
<pre>
unhandledIOPubMessageSignal WidgetManager {comm_target_name: 'jupyter.widget', _models: {…}, _restored: Signal, _restoredStatus: true, _handleCommOpen: ƒ, …} {channel: 'iopub', header: {…}, parent_header: {…}, metadata: {…}, content: {…}, …}
</pre>
</details>

Thank you for your help and for to the project. Much appreciated!

Best,
Alain

**Comment by echarles** [comment]
@alainlep Thank you very much for the detailed report. I can reproduce the issue and will look at it a soon as I can. To help, can you share the exact version number (0.7.14?) for which that was working fine?

**Comment by echarles** [comment]
Just tried with 0.7.14 and the issue shows up also. Trying to understand if it is a regression, or a bug that was already there.

**Comment by pplonski** [comment]
I don't think it is a bug. This is the same behavior as in Jupyter Lab, you need to manually re-execute cell to see the change.

**Comment by alainlep** [comment]
Hi,

@echarles ,  thanks for your quick response, it was working in version 0.5.0

@pplonski Its after following theses steps

1 - Run the first cell to display the slider
2 - Change the slider's value in the first cell.
3 - Execute the second cell to display the slider value

I confirm its working in Jupyterlab and Jupyter-ui version 0.5.0, it no longer working in version 0.8.0, I can’t tell which version introduced it.

Thanks


Alain

**Comment by echarles** [comment]
Yep, I will try to fix that in the coming week. Thx again both.

**Comment by echarles** [comment]
I have released 0.8.2 that fixes this issue. Will wait a bit for feedback before closing.

**Comment by alainlep** [comment]
Thanks! I will have a look soon!

**Comment by alainlep** [comment]
Hi @echarles,

I just tested the fix and it's working great now! Thanks!

Alain

**Comment by echarles** [comment]
Super! I will close this as resolved.
