### ISSUE TITLE
How to enable fast refresh

### ISSUE THREAD

**Issue by markwindsorr** [datalayer/jupyter-ui#152]
Looking for a way to have code changes automatically reflected in the browser. Everything compiles fine but I need to yarn build + yarn start everytime I need to do a code change. Running the development server does not work either.

**Comment by echarles** [comment]
Strange. Are you running the yarn command from the jupyter-ui repository (in which folder?) or from you own repo (declaring jupyte-ui as a dep?)

**Comment by markwindsorr** [comment]
@echarles I tried both. I was using next js and running `yarn jupyter:ui:nextjs` from the root. Also tried with yarn dev and yarn start from the example folder

**Comment by echarles** [comment]
@markwindsorr I have pushed on https://jupyter-ui.datalayer.tech/docs/develop/develop the following text. Does it help?

While running those example, hot reload is supported:

- Changing the source code of the example and your browser should reflect those changes.
- If you need to change the core react package '@datalayer/jupyter-react', you will need to run yarn watch in the 'packages/react' folder.

**Comment by markwindsorr** [comment]
@echarles Thanks for the quick response. I can't seem to get it to work, everything else works fine, it just won't seem to re-render upon saving a file.

**Comment by echarles** [comment]
This is a quick demo to change the page title for the next.js example (started with `yarn jupyter:ui:nextjs` from the root folder).

[Screencast from 26-12-23 08:15:37.webm](https://github.com/datalayer/jupyter-ui/assets/226720/e97262dd-47d3-44a6-97d1-579c51862e3b)

**Comment by echarles** [comment]
I have just pushed https://github.com/datalayer/jupyter-ui/commit/4c8f6e1f50b934e2cf842fe66d529d1b4269f7d0 to revert the version used in the main source tree to 0.8.1. This will be needed if you need to change the core jupyter-react source and see the change in the examples cc/ @fcollonval

**Comment by echarles** [comment]
> currently using vscode dev containers. 

Good to know, I don't use that, so there may be indeed an issue with that setup. I need to try that (tomorrow based on my agenda).

> Also, are you able to run the full notebook at once or can you just run cell by cell?

I usually run cell by cell. I will need to double check for the complete run.

**Comment by markwindsorr** [comment]
@echarles Update, it works without the dev container
