### ISSUE TITLE
How to specify the content of the notebook?

### ISSUE THREAD

**Issue by chenjpu** [datalayer/jupyter-ui#153]
```
<Notebook
              uid={NOTEBOOK_UID}
              model={notebookContent} //path
              CellSidebar={CellSidebar}
              />
```

**Comment by echarles** [comment]
This is documented on https://jupyter-ui.datalayer.tech/docs/components/notebook. Does it help?

This is what it takes to create a Notebook. In this first example, the Jupyter Server will be fetched for the test.ipynb notebook "ipynb" file content.

```ts
<Jupyter terminals={true} collaborative={true}>
  <Notebook path="test.ipynb" />
</Jupyter>
```

Alternatively, you can get a notebook "ipynb" content from any JSON file compatible with the INotebookContent interface.

```ts
import { INotebookContent } from '@jupyterlab/nbformat';
import nbformat from "./NotebookExample.ipynb.json";

<Jupyter terminals={true} collaborative={true}>
  <Notebook nbformat={nbformat as INotebookContent} />
</Jupyter>
```

**Comment by chenjpu** [comment]
Thanks, I just found the api definition too

**Comment by chenjpu** [comment]
@echarles JupyterLab App Component How to specify the nbformat?

**Comment by echarles** [comment]
There is not such a feature for the JupyterLabApp component as it completely rely on the JupyterLab plugins which does not support that.

It could be solved with a custom Content Manager, but it should be implemented.

I have opened https://github.com/datalayer/jupyter-ui/issues/154 to track that feature.

**Comment by chenjpu** [comment]
Using nbformat, I found that a ```ping.iyynb``` file is created on the notebook server end. Can I turn this off?
