### ISSUE TITLE
[DISCUSS] Usage of @jupyter/web-components

### ISSUE THREAD

**Issue by echarles** [datalayer/jupyter-ui#168]
https://github.com/datalayer/jupyter-ui/commit/57bc633119332decd43c189a2c0ac94ab0892ec5 has added `@jupyter/web-components` as dependency to allow the `KernelVariables` component to reuse an existing Lumino implementation and show the variables tables.

![Screenshot from 2024-01-08 08-35-45](https://github.com/datalayer/jupyter-ui/assets/226720/900088df-20ad-4326-80fd-323c3a3a7fa5)

This brings an additional dependency, that is a full widget toolkit aside the existing primer one we are already using.

The additional weight will any be needed as JupyterLab is now also using that widget toolkit.

The discussion is more about how to ensure the displayed widgets remain coherent.

**Comment by fcollonval** [comment]
Jupyter toolkit is themed according to the JupyterLab theme color scheme.
The goal of the toolkit is to be consistent in look and feel with the current JupyterLab UI.

**Comment by echarles** [comment]
Thank you for the background information @fcollonval. Closing this as solved/answered.
