### ISSUE TITLE
Preinstalling Libraries when using a notebook component rather than JupyterLabs component

### ISSUE THREAD

**Issue by markwindsorr** [datalayer/jupyter-ui#193]
Looking for a way to use a notebook component that already has preinstalled libraries so that I can use it without having to pip install whatever library I need

**Comment by echarles** [comment]
Hi @markwindsorr Are you willing to e.g be able to use matplotlib when you run the code. In that case, it is a requirement put on the Jupyter Kernel side, rather that on the UI or env "server".

You may expand the list of ideas you shared no https://github.com/datalayer/jupyter-ui/issues/124#issuecomment-1891187479 with that.
