### ISSUE TITLE
Creating Custom Toolbar | Sidebar

### ISSUE THREAD

**Issue by dbhagesh** [datalayer/jupyter-ui#196]
## Description
As an end user of Jupyter-ui, i want to be allowed to use my own custom toolbar / sidebar.
But when trying to pass custom made toolbar / sidebar. I get this.
![image](https://github.com/datalayer/jupyter-ui/assets/32410360/cc230568-f8d2-46ba-ad4d-9daaaf114f3a)

## Reproduce
1. Use Jupyter-react as a client.
2. Create a simple toolbar file (just having plain divs)
3. Pass that toolbar to Toolbar prop.
4. See the above error

**Comment by igloo1505** [comment]
That's not an issue with this repo that's an issue with your code and a general React error. Do you have it in a repo if you still haven't figured it out?
