### ISSUE TITLE
Markdown collapsing instead of rendering.

### ISSUE THREAD

**Issue by markwindsorr** [datalayer/jupyter-ui#199]
## Description

I pulled the react package files into my project. Everything is working fine except running a markdown cell. When I run the cell, the cell seems to collapse instead of rendering.

## Reproduce

1. Pull react files into a next js project.
2. Run a markdown cell.

https://github.com/datalayer/jupyter-ui/assets/23028549/0a6a363e-a43f-414a-a2fa-9f213ae4bafa

**Comment by echarles** [comment]
Just tried with the next.js example in the example folder and I can not reproduce this issue.

[Screencast from 02-19-2024 08:44:12 AM.webm](https://github.com/datalayer/jupyter-ui/assets/226720/f44d75f5-6870-4f21-8f7c-aebbb8adc164)
