### ISSUE TITLE
Global CSS cannot be imported from within node_modules.

### ISSUE THREAD

**Issue by VisheshNucleusTeq** [datalayer/jupyter-ui#206]
## Description

```
error - ./node_modules/@datalayer/jupyter-react/lib/components/commands/CommandsAdapter.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules/@datalayer/jupyter-react/lib/components/commands/CommandsAdapter.js

Import trace for requested module:
./node_modules/@datalayer/jupyter-react/lib/components/commands/CommandsAdapter.css
./node_modules/@datalayer/jupyter-react/lib/components/commands/CommandsAdapter.js
./node_modules/@datalayer/jupyter-react/lib/components/commands/Commands.js
./node_modules/@datalayer/jupyter-react/lib/index.js
./components/NotebookComponent.tsx
```

"@datalayer/icons-react": "^0.3.0",
    "@datalayer/jupyter-react": "^0.10.0",
    "@datalayer/primer-addons": "^0.3.0",

<img width="552" alt="Screenshot 2024-04-16 at 3 11 28 AM" src="https://github.com/datalayer/jupyter-ui/assets/67576528/b9cc3e13-6e95-4426-acec-b900116e78cd">

**Comment by echarles** [comment]
Hi @VisheshNucleusTeq Can you give us a bit more context: is it a a next.js app, or create-react-app, or a simple webpack, or vite.js? Can you share the full package.json so we can try also?

**Comment by VisheshNucleusTeq** [comment]
This Is resolved need to update the version and made changes the code structure

**Comment by epshone** [comment]
@VisheshNucleusTeq I'm having the same issue getting this to run in the pages dir. Are you able to share your config?
