### ISSUE TITLE
How to configure adding Teradata AI Unlimited custom renderer and sqlhighlighter

### ISSUE THREAD

**Issue by box-turtle** [datalayer/jupyter-ui#211]
### Problem

* I need to support a custom Teradata AI Unlimited kernel that includes a custom resultset renderer for mime type `application/vnd.teradata.resultset`. I have the code for the renderer but I don't know how to configure the jupyter-ui notebook to use it to handle those mime types. 
* Ditto for the custom Teradata SQL highlighter package - is there documentation on how to add that as well?

### Proposed Solution

* Maybe there is a way to use the JupyterLabApp or JupyterLabAppAdapter for this, but documentation is sparse and I'm pretty new to Jupyter notebooks.

### Additional context

* This is a fantastic project!

**Comment by echarles** [comment]
Hi @box-turtle Thx a lot for the kind words. I am just discovering https://downloads.teradata.com/download/tools/teradata-ai-unlimited-jupyter-kernel - Is that a jupyterlab extension one can freely install?

Agree, the way to configure JupyterLabApp needs more documentation and love. For now, you would have to look at the examples, like https://github.com/datalayer/jupyter-ui/blob/main/packages/react/src/examples/JupyterLabHeadlessApp.tsx where some custom mimeExtensions renderers (in that case the plotly one) are added.

**Comment by box-turtle** [comment]
The kernel is in pre-release form now, not sure what the final license will be, but you would have to have access to a Teradata server to run it.

thanks for the quick feedback! So it looks like JupyterLabApp is basically a configuration element I can use to add those registrations. Will give it a try!

**Comment by box-turtle** [comment]
Using the JupyterLabApp I am getting 404 errors for these extensions - is there a way for me to remove these dependencies as I don't need them for my app?

<img width="1059" alt="image" src="https://github.com/datalayer/jupyter-ui/assets/3999743/617ad16d-106c-4c41-92a2-73ea81ebb6f1">

**Comment by box-turtle** [comment]
Previously my app structure was 

```
<Jupyter ...>
    <Notebook .../>
</Jupyter
```

I am a bit confused as to how the <JupyterLabApp> component functions - would it replace my `<Notebook>` component in the structure above? Or be an additional child element of `<Jupyter>`?

Is `<JupyterLabApp>` going to render the entire Jupyter UI?

**Comment by echarles** [comment]
This would be indeed 

```
<Jupyter ...>
    <Notebook .../>
</Jupyter>
```

We need to better document that, but you need to also update the index.html some props. Not why it is needed, not sure if it will fix your issues, but good to let you know. The config is https://github.com/datalayer/jupyter-ui/blob/aa717d4c217ae1c33f32835cc489549dee3bb756/packages/react/public/index.html#L19-L31

**Comment by echarles** [comment]
(specifically appUrl, themesUrl...)

**Comment by box-turtle** [comment]
Figured it out! I just needed to import the Teradata resultset renderfactory and add it to the `renderers` prop of Notebook.

```
          <Notebook
            nbformat={nbformat}
            uid={NOTEBOOK_UID}
            cellSidebarMargin={0}
            renderers={[tdRenderFactory]}
            height="800px"
          />
```

<img width="762" alt="image" src="https://github.com/datalayer/jupyter-ui/assets/3999743/2a40418b-1f5d-4ec5-82fa-29facd0f6faa">

Thanks for your help!

**Comment by echarles** [comment]
Awesome @box-turtle Happy it worked out.
