### ISSUE TITLE
Autocomplete does not work in notebook in examples

### ISSUE THREAD

**Issue by wxirxn-bifrost** [datalayer/jupyter-ui#212]
## Description

In the [Next.js example](https://github.com/echarles/jupyter-nextjs-example), the autocomplete widget does not show up when pressing tab on a line in any cell in a notebook. The completer is invoked, but no options show up.

I've tried all `@datalayer/jupyter-react` versions from 0.9.5 to 0.10.0.

In addition, on 0.10.0, I can't seem to run any cells in any notebook.

## Reproduce

Fresh install and build:
1. Clone the Next.js example
2. Install packages
3. Build and run the Notebook example

## Expected behavior

Completer widget should show up when pressing tab while editing a cell in a notebook

## Context

- Datalayer version: 0.9.5-0.10.0
- Operating System and version: Windows 11
- Browser and version: Chrome & Safari

<details><summary>Browser Output</summary>
<pre>
Kernel Manager is Ready KernelManager {_isDisposed: false, _disposed: Signal, serverSettings: {…}, _isReady: true, _kernelConnections: Set(0), …}
JupyterContext.js:182 Starting Kernel Name: python
JupyterContext.js:200 Kernel is Ready Kernel {_clientId: '4324e694-a772-4359-93c5-1ea8a9c2b6f3', _connectionStatus: 'connected', _id: '9e524afc-03a9-4217-a83b-a0464a409bac', _info: undefined, _kernelConnection: KernelConnection, …}
labicon.js:169 SVG HTML was malformed for LabIcon instance.
name: ui-components:ellipses, svgstr: [object Object]
resolveSvg @ labicon.js:169
_initSvg @ labicon.js:456
get svgElement @ labicon.js:342
element @ labicon.js:293
Placeholder @ placeholder.js:69
InputPlaceholder @ placeholder.js:105
initializeDOM @ widget.js:511
initializeDOM @ widget.js:811
set placeholder @ widget.js:219
onBeforeAttach @ widget.js:548
processMessage @ index.es6.js:1275
invokeHandler @ index.es6.js:420
sendMessage @ index.es6.js:174
onBeforeAttach @ index.es6.js:1988
processParentMessage @ index.es6.js:1900
notifyLayout @ index.es6.js:1328
processMessage @ index.es6.js:1274
invokeHandler @ index.es6.js:420
sendMessage @ index.es6.js:174
onBeforeAttach @ index.es6.js:1988
onBeforeAttach @ index.es6.js:4686
processParentMessage @ index.es6.js:1900
notifyLayout @ index.es6.js:1328
processMessage @ index.es6.js:1274
invokeHandler @ index.es6.js:420
sendMessage @ index.es6.js:174
onBeforeAttach @ index.es6.js:1988
onBeforeAttach @ index.es6.js:4686
processParentMessage @ index.es6.js:1900
notifyLayout @ index.es6.js:1328
processMessage @ index.es6.js:1274
invokeHandler @ index.es6.js:420
sendMessage @ index.es6.js:174
attach @ index.es6.js:1704
eval @ Lumino.js:25
commitHookEffectListMount @ react-dom.development.js:23145
commitPassiveMountOnFiber @ react-dom.development.js:24921
commitPassiveMountEffects_complete @ react-dom.development.js:24886
commitPassiveMountEffects_begin @ react-dom.development.js:24873
commitPassiveMountEffects @ react-dom.development.js:24861
flushPassiveEffectsImpl @ react-dom.development.js:27034
flushPassiveEffects @ react-dom.development.js:26979
eval @ react-dom.development.js:26764
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Show 46 more frames
Show less
Kernel.js:102 Kernel Info {path: 'kernel-23414175-4751-4008-b458-673a68f54c41', id: '9e524afc-03a9-4217-a83b-a0464a409bac', clientId: '4324e694-a772-4359-93c5-1ea8a9c2b6f3', sessionId: 'c1e3e879-01c3-4479-a796-e10e6ff1a3b9', kernelInfo: {…}}
NotebookAdapter.js:284 Previous Kernel Connection null
NotebookAdapter.js:286 Current Kernel Connection null
labicon.js:169 SVG HTML was malformed for LabIcon instance.
name: ui-components:collapse, svgstr: [object Object]
resolveSvg @ labicon.js:169
_initSvg @ labicon.js:456
get svgElement @ labicon.js:342
element @ labicon.js:293
updatePromptOverlayIcon @ widget.js:1054
eval @ widget.js:796
invokeSlot @ index.es6.js:563
emit @ index.es6.js:521
emit @ index.es6.js:120
eval @ widget.js:340
requestAnimationFrame (async)
_addPromptOverlay @ widget.js:339
OutputArea @ widget.js:192
CodeCell @ widget.js:782
createCodeCell @ widget.js:898
_createCodeCell @ widget.js:592
_insertCell @ widget.js:557
_onCellsChanged @ widget.js:512
_onCellsChanged @ widget.js:997
invokeSlot @ index.es6.js:563
emit @ index.es6.js:521
emit @ index.es6.js:120
eval @ celllist.js:142
_onSharedModelChanged @ celllist.js:142
invokeSlot @ index.es6.js:563
emit @ index.es6.js:521
emit @ index.es6.js:120
YNotebook._onYCellsChanged @ ynotebook.js:180
callAll @ function.js:37
callEventHandlerListeners @ yjs.mjs:2103
callTypeObservers @ yjs.mjs:5090
_callObserver @ yjs.mjs:5895
eval @ yjs.mjs:3372
callAll @ function.js:37
cleanupTransactions @ yjs.mjs:3402
transact @ yjs.mjs:3528
transact @ yjs.mjs:664
transact @ ydocument.js:172
fromJSON @ ynotebook.js:462
fromJSON @ model.js:291
eval @ context.js:578
Promise.then (async)
_revert @ context.js:572
initialize @ context.js:218
setupAdapter @ NotebookAdapter.js:345
NotebookAdapter @ NotebookAdapter.js:101
eval @ Notebook.js:57
Promise.then (async)
newAdapterState @ Notebook.js:56
eval @ Notebook.js:120
commitHookEffectListMount @ react-dom.development.js:23145
commitPassiveMountOnFiber @ react-dom.development.js:24921
commitPassiveMountEffects_complete @ react-dom.development.js:24886
commitPassiveMountEffects_begin @ react-dom.development.js:24873
commitPassiveMountEffects @ react-dom.development.js:24861
flushPassiveEffectsImpl @ react-dom.development.js:27034
flushPassiveEffects @ react-dom.development.js:26979
eval @ react-dom.development.js:26764
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Show 58 more frames
Show less
NotebookAdapter.js:284 Previous Kernel Connection null
NotebookAdapter.js:286 Current Kernel Connection KernelConnection {_id: '9e524afc-03a9-4217-a83b-a0464a409bac', _createSocket: ƒ, _onWSOpen: ƒ, _onWSMessage: ƒ, _onWSClose: ƒ, …}
NotebookAdapter.js:288 The current Kernel Connection does not handle Comms 9e524afc-03a9-4217-a83b-a0464a409bac
eval @ NotebookAdapter.js:288
invokeSlot @ index.es6.js:563
emit @ index.es6.js:521
emit @ index.es6.js:120
_handleNewSession @ sessioncontext.js:637
_changeKernel @ sessioncontext.js:586
await in _changeKernel (async)
changeKernel @ sessioncontext.js:399
await in changeKernel (async)
setupAdapter @ NotebookAdapter.js:236
NotebookAdapter @ NotebookAdapter.js:101
eval @ Notebook.js:57
Promise.then (async)
newAdapterState @ Notebook.js:56
eval @ Notebook.js:120
commitHookEffectListMount @ react-dom.development.js:23145
commitPassiveMountOnFiber @ react-dom.development.js:24921
commitPassiveMountEffects_complete @ react-dom.development.js:24886
commitPassiveMountEffects_begin @ react-dom.development.js:24873
commitPassiveMountEffects @ react-dom.development.js:24861
flushPassiveEffectsImpl @ react-dom.development.js:27034
flushPassiveEffects @ react-dom.development.js:26979
eval @ react-dom.development.js:26764
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Show 23 more frames
Show less
NotebookAdapter.js:290 The current Kernel Connection is updated to enforce Comms support true
</pre>
</details>

**Comment by echarles** [comment]
Thx for reporting. The integration with next-js is a bit more tricky than the others, and tbh has not been our priority. Due to the amount of report on this, I will prioritize this the next week. Thx again.

**Comment by echarles** [comment]
@wxirxn-bifrost I have bumped the deps (as basic maintenance) and the example repo and the auto complete works for me.

![Image](https://github.com/datalayer/jupyter-ui/assets/226720/789f8e4f-6134-4e6a-9834-b5b509f802a2)

PS: I have moved the repo to https://github.com/datalayer-examples/jupyter-nextjs-example

**Comment by wxirxn-bifrost** [comment]
The project works for me now - thanks!
