### ISSUE TITLE
Cannot install Docusuarus Plugin 

### ISSUE THREAD

**Issue by lyleaigbedion** [datalayer/jupyter-ui#221]
## Description

On Node v18.18.0 and npm 9.8.1 

Running `npm i @datalayer/jupyter-docusauru-plugin`

returns this error 

npm ERR! code ETARGET
npm ERR! notarget No matching version found for @primer/react@0.0.0-20230912151940.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

## Reproduce

1. Run `npm i @datalayer/jupyter-docusauru-plugin`

## Expected behavior

Able to install

## Context

- Datalayer Docusaurus plugin version: 0.0.9
- Operating System and version: MacOS Sonoma 14.4.1
- Browser and version: Chrome 124.0.6367.203 (Official Build) (arm64)

**Comment by echarles** [comment]
@lyleaigbedion Thx for opening this issue. I have pushed a new 0.1.0 release, could you try? https://www.npmjs.com/package/@datalayer/jupyter-docusaurus-plugin/v/0.1.0

PS: there is a typo in the package you shared, jupyter-docusauru-plugin` it should be `jupyter-docusauru-plugin` - no sure if this was the issue.

**Comment by lyleaigbedion** [comment]
@echarles Thanks for the quick turnaround! I'm able to install it!
