### ISSUE TITLE
Being redirected using docusaurus plugin 

### ISSUE THREAD

**Issue by lyleaigbedion** [datalayer/jupyter-ui#223]
## Description

Navigating to the mdx page with `<JupyterCell/>` invoked redirects to http://localhost:8686/api/jupyter/login?next=http://localhost:3000/docusaurus/intro

With a 404 not found. 

I am working on a new docusaurus site outside of the jupyter-ui directory 

Using this example: 

```js 
import JupyterCell from '@theme/JupyterCell';

<JupyterCell 
  source={`print('Hello world')
for i in range(10):
  print(i)
`}
  token='60c1661cc408f978c309d04157af55c9588ff9557c9380e4fb50785750703da6'
  serverHttpUrl='http://localhost:8686/api/jupyter'
  serverWsUrl='ws://localhost:8686/api/jupyter'
/>

```

## Reproduce

1. Go to `jupyter-ui` directory
2. Run `./dev/sh/start-jupyter-server.sh`
3. Run 'npm start' in the docusaurus directory
4. Navigate to the page that contains the JupyterCell component

## Expected behavior

Renders the jupyter notebook example

## Context

- Datalayer Docusaurus plugin version: 0.1.0
- Operating System and version: MacOS Sonoma 14.4.1
- Browser and version: Chrome 124.0.6367.203 (Official Build) (arm64)

**Comment by echarles** [comment]
@lyleaigbedion I have opened https://github.com/datalayer/jupyter-ui/pull/224 to fix the server url used in the examples (see [these changes](https://github.com/datalayer/jupyter-ui/pull/224/files)).

The is a rest of the changes made for https://github.com/datalayer/jupyter-ui/issues/214

Optionally, you can use the cloud servers with

```
...
  serverHttpUrl='https://oss.datalayer.run/api/jupyter-kernels'
  serverWsUrl='wss://oss.datalayer.run/api/jupyter-kernels'
...
```
