### ISSUE TITLE
Server URL issue with the new URLs

### ISSUE THREAD

**Issue by markwindsorr** [datalayer/jupyter-ui#228]
## Description
I'm getting this issue when trying to use the new URLs. It works some of the time.

![image](https://github.com/datalayer/jupyter-ui/assets/23028549/7c40744a-d94e-462b-8308-147435031eff)

**Comment by echarles** [comment]
@markwindsorr The url has changed again to oss.datalayer.run/api/jupyter-server (jupyter-server, not jupyter-kernels)

Could you try again, sorry for that... we should stabilize now.

**Comment by markwindsorr** [comment]
@echarles awesome, that worked and thanks for such a quick response
