### ISSUE TITLE
Inquiry About Pre-run some code in Notebooks 

### ISSUE THREAD

**Issue by littlekeixi** [datalayer/jupyter-ui#242]
Hi Admin,

Firstly, I want to say a big thank you to your team. I'm excited to use your library in my app. 

I'm trying to allow users to access notebooks within my application using your library. Yet, I also aim to pre-run certain code snippets to inject specific functions or variables that would enhance the user experience during their session.

I've scanned through the documentation but haven't stumbled upon a method to execute code within the current notebook without displaying the cell to the user. Could you kindly provide guidance on how I might achieve this?

Thank you

**Comment by wxirxn-bifrost** [comment]
@littlekeixi did you figure out how to do this? I'm looking to do something similar. Thanks in advance!

**Comment by echarles** [comment]
@wxirxn-bifrost There is a ìnitCode` prop on the Jupyter context. Have you tried that.

btw we should enroll another way as the Jupyter context will be deprecated at some time, in favor of a the simpler zustand state.

**Comment by littlekeixi** [comment]
Thanks Eric. I did try initCode prop and successfully inject the code to
the notebook.

Vào Th 3, 11 thg 6, 2024 lúc 16:31 Eric Charles ***@***.***>
đã viết:

**Comment by echarles** [comment]
Awesome :+1:
