### ISSUE TITLE
Problems using datalayer cell component from React App with local Jupyter server - got redirect to jupyter server on initialization

### ISSUE THREAD

**Issue by sok82** [datalayer/jupyter-ui#244]
## Description

Unable to connect to local Jupyter Server from basic example React application - with a single Jupyter Cell.
Instead of showing application component I'm redirected to login page and then to Jupyter server page.

## Application context and environment

1. I have Jupyter server installed locally and running on http://localhost:8888. 
(installed it with `pip3 install jupyter_server` and run with `jupyter server` commands)

2.  Created React application insipired by Cell Example from [here](https://github.com/datalayer-examples/jupyter-react-webpack-example/tree/main/src/examples/cell)

```TypeScript

import {Cell, Jupyter, selectCell} from '@datalayer/jupyter-react';

const CellPreview = () => {
  const cell = selectCell();
  return (
    <>
      <div>source: {cell.source}</div>
      <br/>
      <div>kernel available: {String(cell.kernelAvailable)}</div>
      <br/>
    </>
  )
}

const CellComponents = () => (
  <>
    <CellPreview/>
    <Cell source="" />
  </>
)


function App() {    
    return (
                <div className="App">
                  <Jupyter 
                    jupyterServerHttpUrl="http://localhost:8888"
                    jupyterServerWsUrl="ws://localhost:8888"
                    jupyterToken="<my_token_here>"     
                    lite={false}
                    useRunningKernelIndex={-1}
                    startDefaultKernel={true}
                    terminals={false}             
                  >
                    <CellComponents/>
                  </Jupyter>
                </div>
  );
}

```
3. I didn't copy any other settings from example (like those in index.html)

## Reproduce

1. Starting Jupyter server by `jupyter server` command
2. Copying token listed in output to ` jupyterToken` field
3. Starting React application by `npm start` 
4. When application starts in browser i see that page on port http://localhost:3000 is being loaded
5. After that redirect to localhost:8888 occurs with message 'Jupyter server is running' 
![image](https://github.com/datalayer/jupyter-ui/assets/53971158/c1ce14bf-2c4d-4d2e-9cd9-f781a165055f)
6. Jupyter server log is shown below

Also tried starting Jupyter Lab and Jupyter Notebook with same results.

## Expected behavior
Page with a Jupyter cell is displayed on page 

## Context
Here is jupyter server log
```
SK-MacBook-Air:~ sk$ jupyter server
/Users/sk/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
[I 2024-06-13 13:36:51.384 ServerApp] Extension package jupyterlab took 0.2629s to import
[I 2024-06-13 13:36:52.162 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2024-06-13 13:36:52.168 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2024-06-13 13:36:52.175 ServerApp] jupyterlab | extension was successfully linked.
[I 2024-06-13 13:36:53.260 ServerApp] notebook_shim | extension was successfully linked.
[I 2024-06-13 13:36:53.365 ServerApp] notebook_shim | extension was successfully loaded.
[I 2024-06-13 13:36:53.369 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2024-06-13 13:36:53.370 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2024-06-13 13:36:53.373 LabApp] JupyterLab extension loaded from /Users/sk/Library/Python/3.9/lib/python/site-packages/jupyterlab
[I 2024-06-13 13:36:53.374 LabApp] JupyterLab application directory is /Users/sk/Library/Python/3.9/share/jupyter/lab
[I 2024-06-13 13:36:53.375 LabApp] Extension Manager is 'pypi'.
[I 2024-06-13 13:36:53.395 ServerApp] jupyterlab | extension was successfully loaded.
[I 2024-06-13 13:36:53.396 ServerApp] Serving notebooks from local directory: /Users/sk
[I 2024-06-13 13:36:53.396 ServerApp] Jupyter Server 2.14.1 is running at:
[I 2024-06-13 13:36:53.396 ServerApp] http://localhost:8888/?token=<.....my token here>
[I 2024-06-13 13:36:53.396 ServerApp]     http://127.0.0.1:8888/?token=<...my token here>
[I 2024-06-13 13:36:53.396 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2024-06-13 13:36:53.403 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///Users/sk/Library/Jupyter/runtime/jpserver-4162-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=e431063fa4396b747309e68d005a13b322aa2cd8feeacc64
        http://127.0.0.1:8888/?token=e431063fa4396b747309e68d005a13b322aa2cd8feeacc64
[I 2024-06-13 13:36:54.305 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[W 2024-06-13 13:38:41.124 ServerApp] Not allowing login redirect to 'http://localhost:3000/'
[I 2024-06-13 13:38:41.129 ServerApp] 302 GET /login?next=http://localhost:3000/ (f1a0a94364f641dd8769b098622b4c31@::1) 31.62ms
[W 2024-06-13 13:38:55.123 ServerApp] Not allowing login redirect to 'http://localhost:3000/'
[I 2024-06-13 13:38:55.123 ServerApp] 302 GET /login?next=http://localhost:3000/ (f1a0a94364f641dd8769b098622b4c31@::1) 1.83ms
```

**Comment by sok82** [comment]
Solved this. Sorry for disturbing.

Recipe is quite simple 
1. Generate config file by  command `jupyter server --generate-config.`
2. Open generated `jupyter_server_config.py` (in my case located in `.jupyter` folder in current user root folder)
3. **KEY POINT!!!** Include security settings listed [here](https://jupyter-ui.datalayer.tech/docs/deployments/jupyter-server/) in config file
4. Restart server by command from terminal `jupyter server`

**Comment by echarles** [comment]
Thx @sok82

**Comment by JDMart04** [comment]
I am also experiencing this problem. I have the same settings in the jupyter_server_config.py file, or at least nearly the same.
Do you know which setting in particular was causing the failed redirects?

I am also running into an issue where I still have to enter the token via the jupyter login page even though I have set it in index.html. Once logged in, it gives a cookie that works until the server is restarted? I am not sure if these issues are related.

One last additional complexity is I am running the Jupyter server in a Docker container.

**Comment by echarles** [comment]
@JDMart04 How does you jupyter server config looks like? You should map the requirements described on https://jupyter-ui.datalayer.tech/docs/deployments/jupyter-server/

**Comment by JDMart04** [comment]
Here is the current version of my jupyter_server_config.py
```python
"""Configuration for the Jupyter development server."""

#################
# Logging
#################

c.ServerApp.log_level = 'DEBUG'

#################
# Network
#################

c.ServerApp.port = 8888
c.ServerApp.port_retries = 0


c.IdentityProvider.token = '60c1661cc408f978c309d04157af55c9588ff9557c9380e4fb50785750703da6'

#################
# Security
#################

c.ServerApp.disable_check_xsrf = False

ORIGIN = '*'

c.ServerApp.allow_origin_pat = '.*'
c.ServerApp.allow_credentials = True
c.ServerApp.tornado_settings = {
  'headers': {
    # 'Access-Control-Allow-Origin': ORIGIN,
    # 'Access-Control-Allow-Methods': 'GET, PUT, POST, PATCH, DELETE, OPTIONS',
    'Access-Control-Allow-Methods': '*',
    'Access-Control-Allow-Headers': 'Accept, Accept-Encoding, Accept-Language, Authorization, Cache-Control, Connection, Content-Type, Host, Origin, Pragma, Referer, sec-ch-ua, sec-ch-ua-mobile, sec-ch-ua-platform, Sec-Fetch-Dest, Sec-Fetch-Mode, Sec-Fetch-Site, Upgrade, User-Agent, X-XSRFToken, X-Datalayer, Expires',
    'Access-Control-Allow-Credentials': 'true',
    'Content-Security-Policy': f"frame-ancestors 'self' {ORIGIN} ",
  # }
  },
  'cookie_options': {
    'SameSite': 'None',
    'Secure': True
  }
}


c.IdentityProvider.cookie_options = {
  "SameSite": "None",
  "Secure": True,
}

```

and the relevant section of my index.html

```javascript
    <script id="datalayer-config-data" type="application/json">
      {
        "jupyterServerHttpUrl": "http://localhost:8888",
        "jupyterServerWsUrl": "ws://localhost:8888",
        "jupyterServerUrl": "http://localhost:8888",
        "jupyterToken": "60c1661cc408f978c309d04157af55c9588ff9557c9380e4fb50785750703da6"
      }
    </script>
```

I can access the REST API without any issues using localhost:8888/api. I am not sure if datalayer-ui uses this or not. I see the example sets the bae URLs to be api/jupyter-server. I have put in that as a setting, but it does not appear to be getting that far in the process before I get the 302 response and the corresponding "Not allowing login redirect".

One option I have seen is to set
c.ServerApp.allow_remote_access = True

but this has not worked for me either.
Thank you for your assistance @echarles

**Comment by JDMart04** [comment]
User error. I did not indicate the correct location for the jupyer_server_config.py file when starting up Jupyter. I was surprised that no message was returned about not finding file during startup.
Thank you for your patience @echarles. This is a great project.
