### ISSUE TITLE
Get the output of a Cell component

### ISSUE THREAD

**Issue by MarcosVn** [datalayer/jupyter-ui#249]
I am rendering individual `<Cell>` components and intend to manually sync them in a notebook on my server, using something like `serviceManager.contents.save`. For this, I would like to get also the `output` besides the `source` of the already executed cells.

Is there any way to extract this from a `<Cell>`? Or is there a more appropriate way to do this that I should be following?

**Comment by sok82** [comment]
Hi @MarcosVn ,
Glad you've asked
+1
I also interested in this feature.

And more specifically - i'm interested in how can I just send code to Jupyter and 
1. Get the output (in JSON)
2. Render output in a widget

@echarles 
Maybe you can point on some examples of how this can be achieved?
Or maybe some docs to read?

**Comment by echarles** [comment]
@sok82 @MarcosVn I have opened https://github.com/datalayer/jupyter-ui/pull/251 to give examples

For a Cell component:

```
 console.log('Cell Outputs', cellStore.adapter?.codeCell.outputArea.model.toJSON());
```

For an Output component

```
console.log('Outputs 1', outputStore.getAdapter(SOURCE_ID_1)?.outputArea.model.toJSON());
```

PS: Futher to the migration to Zustand, the store API is still evolving - We also need to support a store with mulitple Cells (like we support a store with multiple Outputs)

**Comment by sok82** [comment]
Hey @echarles,
thanks a lot for your quick answer.

I guess it solves my problem.

Looking forward for you guys to merge this PR

**Comment by MarcosVn** [comment]
Hello, @echarles.

Thank you for the feedback. I tested it here, and it worked perfectly.
Something I hadn't clearly noticed is this migration, and soon I was testing, exploring version `0.10.0`.

As far as I'm concerned, the issue can be closed. I will explore `0.11.x` more thoroughly.

**Comment by echarles** [comment]
@sok82 I have just released `@datalayer/jupyter-react` `0.13.0` which has the current main source.

**Comment by echarles** [comment]
You can use `console.log('Outputs 1', outputStore.getAdapter(SOURCE_ID_1)?.outputArea.model.toJSON());` with 0.13.0

**Comment by sok82** [comment]
Hi @echarles ,
I'm testing version 0.14.0. 

Works like a charm, just have one question regarding proper way of reacting to execution events.

What I'm trying to do is
1. Set code to output
2. Trigger execution
3. Catch execution finished event
4. Do some internal logic of my app

At the moment the only way I found to catch event is to connect to output like this
```
      outputAdapter.outputArea.model.changed.connect(handleOutputStateChanged);
```
and in `handleOutputStateChanged` check execution result like this
```
    const handleOutputStateChanged = (source : IOutputAreaModel, changedArgs : IOutputAreaModel.ChangedArgs) => {
        logger.debug(`Got new output for cell with uuid=${props.cellUuid}`, changedArgs);
        if (changedArgs.type !== 'remove') {            
            if (changedArgs.newValues.length > 0) {
                const outputValue = changedArgs.newValues[0];
                if (outputValue.type === 'error') {
                    // Process error....
                }
                else {
                    // Process successful execution....
                }
            }
        }
        else  {
            // Do something else...
        }
    }
```

PROBLEM with this approach 
1. When I have non empty output - everything is OK
2. But when executed code generates no output (i.e  `changedArgs.newValues.length === 0`) I can't be sure that it's ok or not, because first I have signal with `changedArgs.type === 'remove'` that clears output and no new signal that adds output appears


Can you recommend, how can I do it in proper way?

**Comment by fcollonval** [comment]
Hey @sok82 

we could add a state `executionState` by cell in the store.

For example:

```ts
useEffect(() => {
    switch(cell.executionState) {
      case 'running':
        alert('cell is pending execution or running');
      case 'idle':
        alert('no cell execution in progress');
    }
}, [cell.executionState])
```

What do you think?

**Comment by sok82** [comment]
Hey @fcollonval ,

It could be a good idea for those who are using `Cell` itself, but I wonder how it may help me

My case is a bit different
1. Actually I don't use `Cell` component at all - I just use `Output`.
2. I need to react on event - not just checking state

In other words I need some handler that is fired when execution is finished with a status 

Something like
```TypeScript
outputAdapter.executionStateChanged = handleOutputStateChanged;

const handleOutputExecutionStateChanged = (executionState :string, changedArgs? : IOutputAreaModel.ChangedArgs) => {
        switch(executionState) {
              case 'running':
                alert('Output code is pending execution or running');
              case 'success':
                alert('Output code finished successfully  with result ' + changedArgs.newValues);
              case 'error':
                alert('Output code finished with error');
            }
}
```

Your idea of just tracking executionState is also nice, but I wonder how it may help me to catch the moment when execution finished?
Is it 'idle'? And how it differs from being idle before execution started?

**Comment by sok82** [comment]
Hey @fcollonval 

Can you please clarify - is it possible to implement something like I mentioned, or it's better to find another way?

**Comment by echarles** [comment]
Follow-up in https://github.com/datalayer/jupyter-ui/issues/269
