### ISSUE TITLE
Is there a way to send an initial command on opening a notebook

### ISSUE THREAD

**Issue by box-turtle** [datalayer/jupyter-ui#254]
This is more of a support question than a documentation enhancement request, so please ignore if there is not a simple answer.

I thought I saw somewhere in docs or code that there is a way to send an initial code command - for instance some code to connect to a default db - that would not appear in the notebook but would get executed on notebook open. But I can't find it now - does that functionality exist?

Thanks for a great product!

**Comment by echarles** [comment]
That feature exists but needs to be documented. You just have to define the `initCode` props on the `Jupyter` context

```
<Jupyter initCode="x=1">
  <Notebook .../>
</Jupyter>
```

```
  /**
   * Code to be executed silently at kernel startup
   *
   * This is ignored if there is no default kernel.
   */
  initCode?: string;
```

**Comment by box-turtle** [comment]
Thank you Eric!

**Comment by echarles** [comment]
Closing as available and documented in https://jupyter-ui.datalayer.tech/docs/components/context/
