### ISSUE TITLE
 Control session and kernel initialization individually per Cell

### ISSUE THREAD

**Issue by MarcosVn** [datalayer/jupyter-ui#273]
### Problem

* I am developing a web application that uses multiple `<Cell>` components. 
* In my case, I would like to control the initial execution to ensure the order of the cells.
* I am facing the following error, as it seems I might be executing before the session with the individual kernel of each cell is ready:

![image](https://github.com/user-attachments/assets/2bf144ba-003b-4cc4-abb4-ad3b09bcc78a)

### Proposed Solution

* Move the `isKernelAvailable` to `ICellState`, meaning having this control per cell;
* Stop conditioning `isKernelAvailable` to when `autoStart` is `true`, i.e., set it as soon as the session's initialize is completed

### Additional context

I will implement the proposed solution and submit it soon, as it is more important for our use case.
CC: @eric

**Comment by MarcosVn** [comment]
Hey, @echarles, how are you?

I have submitted a PR for this enhancement. Could you review it when possible, please?
Here is some functional evidence of the change: 


https://github.com/user-attachments/assets/512e3ceb-da5b-4d9b-a8f0-a47be926e73b



In this case, I am using the code snippet below in final app to ensure execution in order, based on the state inserted by the flags:
If you agree and could publish a new version with the change, I would be very grateful!

Usage: 
```
const isExecutingRef = useRef(false);
  useEffect(() => {
    if (id) {
      const handleChange = (newState) => {
        if (newState.areAllCellsReady && !isExecutingRef.current) {
          isExecutingRef.current = true;
          cellStore.getState().execute('1');
          cellStore.getState().execute('2');
        }
      };

      // Subscribe to cellStore changes
      const unsubscribe = cellStore.subscribe(handleChange);

      // Cleanup function to unsubscribe on unmount
      return () => {
        unsubscribe();
      };
    }
  }, [id]);
```

**Comment by MarcosVn** [comment]
Hey @echarles, @fcollonval, how are you?

Could you please review the open PR when possible?
I'll be happy and available to make any adjustments needed for integration.

Thank you very much in advance!

**Comment by MarcosVn** [comment]
@eric, as soon as the version with the changes from the PR is published, this issue can be closed.

Thanks again!

**Comment by echarles** [comment]
@MarcosVn 0.16.0 is just published with https://github.com/datalayer/jupyter-ui/pull/276

https://www.npmjs.com/package/@datalayer/jupyter-react/v/0.16.0

**Comment by MarcosVn** [comment]
Thank you, @eric!
As far as I'm concerned, we can close the issue.
