### ISSUE TITLE
Enable hiding \ showing kernel progress bar for output

### ISSUE THREAD

**Issue by sok82** [datalayer/jupyter-ui#275]
### Problem

Kernel progress bar that is visible by default when kernel is not idle looks very strange.

In fact when we execute just one output - EVERY output on the page shows some progress which seems very strange and misleading for me, because I triggered execution of only one specific output

Another issue with this progress bar is it shows progress when kernel is not executing anything AND is not 'idle'. I guess in that state kernel tries to initialize or smth like this but user is seeing some progress which also looks misleading for me

IMHO In any case there must be a chance to hide this progress and replace it by smth else, like with controls and editor

### Proposed Solution

Add `showKernelProgressBar` property on `Output` true by default

### Additional context

I already created [Pull Request](https://github.com/datalayer/jupyter-ui/pull/274) for this

**Comment by echarles** [comment]
Done with https://github.com/datalayer/jupyter-ui/pull/274 Thx a lot @sok82

**Comment by sok82** [comment]
Hey @echarles ,

and when https://github.com/datalayer/jupyter-ui/pull/274 merged would be available on NPM and what would be the version number?

I tried to download version 0.15.0 and I don't see changes here...

**Comment by echarles** [comment]
Hi @sok82 I can cut a release today if you need it.

**Comment by sok82** [comment]
No problem - next week would be ok for me, just tell me when it would be deployed to NPM
