### ISSUE TITLE
Clicking on run in the CellSidebar doesn't do anything

### ISSUE THREAD

**Issue by dhruva89** [datalayer/jupyter-ui#286]
## Description

When I click on run in the CellSidebar after selecting a cell. The cell doesn't execute. In the console I see the following warning:
"NotebookCommands.ts:197 Requesting cell execution without any cell executor defined. Falling back to default execution."

## Reproduce

1. Create a notebook with a cellsidebar. The notebook is connected to a jupyter server running locally.
2. Click on Run in cell sidebar

## Expected behavior
Cell exeecutes and outptut is visible below it.

## Context

- jupyter-react version:0.13.0
- Operating System and version: osx 14.4.1
- Browser and version: Chrome 126.0.6478.183

**Comment by echarles** [comment]
0.13.0 is pretty old, can you bump to latest 0.17.0?
Also, make sure you pin or add resolutions for the jupyterlab dependencies, they have to be aligned.
Which tool are you using: yarn, npm...?

**Comment by dhruva89** [comment]
Still seeing this issue after upgrading to 0.17.0. I'm using npm

**Comment by echarles** [comment]
could you try with yarn? also please check that you set the jupyterlab dependencies resolutions like https://github.com/datalayer/jupyter-ui/blob/3ac5b261927f70a526f777b847ee84afc6ad4b3e/package.json#L81-L198

**Comment by dhruva89** [comment]
Using yarn, and setting the right dependency versions in the project fixed it
