### ISSUE TITLE
Access all actions in jupyterlab's NotebookActions

### ISSUE THREAD

**Issue by wxirxn-bifrost** [datalayer/jupyter-ui#287]
Is it possible to access all the actions in [`NotebookActions`](https://github.com/jupyterlab/jupyterlab/blob/main/packages/notebook/src/actions.tsx) without installing `@jupyterlab/notebook` in my project?

[`NotebookCommands`](https://github.com/datalayer/jupyter-ui/blob/main/packages/react/src/components/notebook/NotebookCommands.ts) does not expose every single function from `NotebookActions` (like `runCells()`), and neither does [`NotebookState`](https://github.com/datalayer/jupyter-ui/blob/main/packages/react/src/components/notebook/NotebookState.ts).

Is there an alternative way to access these actions, and/or plans to allow us to access these actions in the future? Thanks in advance!

**Comment by echarles** [comment]
> Is it possible to access all the actions in [NotebookActions](https://github.com/jupyterlab/jupyterlab/blob/main/packages/notebook/src/actions.tsx) without installing @jupyterlab/notebook in my project?

I you don't install @jupyterlab/notebook you won't be able to use the notebook, hence won't need the NotebookActions. What would be your intent?

**Comment by wxirxn-bifrost** [comment]
I'd like to be able to run a specific cell (using its index) programmatically. `NotebookState` (`useNotebookStore()`) only exposes `run` and `runAll`.

**Comment by echarles** [comment]
The easiest in terms of API would be to add action on the store `runCell(id)`

Another way would be to add more commands in https://github.com/datalayer/jupyter-ui/blob/main/packages/react/src/components/notebook/NotebookCommands.ts
