### ISSUE TITLE
Lite support (pyodide) for Notebook, Cell and Output

### ISSUE THREAD

**Issue by echarles** [datalayer/jupyter-ui#30]
Pyodide kernels are supported by the `Console` component. `Notebook`, `Cell` and `Output` components should also support that.

**Comment by Wrufesh** [comment]
Hi @echarles!

I am trying to use pyodide kernel with jupytor ui.

Do we have any update on this from your side?

Best

**Comment by echarles** [comment]
Thx for asking @Wrufesh 

The Console support pyodide today (just set `lite={true}` in the Jupyter context). @fcollonval and I will take over the support for the other components begin January.

![Screenshot from 2023-12-19 19-29-48](https://github.com/datalayer/jupyter-ui/assets/226720/6aebcf17-d87e-46aa-badd-0e612f550e91)

**Comment by echarles** [comment]
Done with latest commits 🎉 Awesome work done by @fcollonval
