### ISSUE TITLE
Error compiling project with jupyter-react >= 0.18.6 - error with plotly.js dependency

### ISSUE THREAD

**Issue by sok82** [datalayer/jupyter-ui#310]
## Description
When I'm trying to compile project having "@datalayer/jupyter-react": with version >= "0.18.6" I'm getting compile error

```
ERROR in ./node_modules/plotly.js/src/registry.js 256:4-63
Module not found: Error: Can't resolve '../node_modules/maplibre-gl/dist/maplibre-gl.css' in '/Users/sk/Develop/d20/d20-git-repo/d20-web-app-page-editor-ui/node_modules/plotly.js/src'
```

@echarles It seems that this issue is discussed here - https://github.com/plotly/plotly.js/issues/7145 and we need to manage correct version in project dependencies

**Comment by echarles** [comment]
I realized that current main branch has build failure due to a bad import, not related to plotly. I have not faced the one you report. Which toolchain are you using? (yarn, npm, pnpm?)

**Comment by sok82** [comment]
I use NPM. 

I guess that we just need to switch dependency of plotly to v2.35.2 as discussed here - https://github.com/plotly/plotly.js/issues/7145

I can create PR with that

**Comment by echarles** [comment]
Sounds good. Please check that the examples with plotly continue to work. Thx

Btw Yarn is for now the only supported way, happy to learn npm works also for you.

**Comment by sok82** [comment]
@echarles  please check the fix - https://github.com/datalayer/jupyter-ui/pull/311
