### ISSUE TITLE
Execution phase is invalid when output is a stream or has warnings in output list

### ISSUE THREAD

**Issue by sok82** [datalayer/jupyter-ui#314]
## Description
Kernel executor's execution phase is assigned invalid value (`completed_with_error`) when execution completes with warning or execution output is a stream

## Reproduce

1. Execution that has warning - 
Just place code 
```python
import warnings;
warnings.warn('This is a warning message');
print('See warning in output!')
```
in a cell and it is executed with execution phase `completed_with_error`

3. Execution that has stream output
```python
print(2+2)
```
in a cell and it is executed with execution phase `completed_with_error`, besides everything is ok with the code

## Expected behavior

1. Execution that has warning in output must end with separate status `completed_with_warning`
4. Execution that has stream output and have no errors must end with `completed`

@echarles  I will make a PR with fix to this issue

**Comment by echarles** [comment]
Thx @sok82 Just merged the PR. Do you need a release?

**Comment by sok82** [comment]
Thnx @echarles
 yeah, I need release ASAP

**Comment by echarles** [comment]
@sok82 0.18.9 is released with this feature.
