### ISSUE TITLE
Set individual Kernel for Cell component

### ISSUE THREAD

**Issue by MarcosVn** [datalayer/jupyter-ui#332]
### Problem

* I have a custom `Notebook.tsx` component that render the cells through a group of `Cell` components from `jupyter-react`. I would like to configure an individual kernel for each notebook to avoid context conflicts;
  * Exploring the `Cell.tsx` interface, it seems that this is not feasible today, as the `defaultKernel` is used in a fixed manager within the component.

* I'm also currently using `0.17.0` version.

### Proposed Solution

* Allow the `Cell.tsx` to receive a specific kernel through an injected property.

### Additional context

* Possibly related item: https://github.com/datalayer/jupyter-ui/issues/281

**Comment by MarcosVn** [comment]
Hey @echarles, from my side, we can close this issue. Thank you!

**Comment by echarles** [comment]
Great. Thx @MarcosVn
