### ISSUE TITLE
Jupyter React 

### ISSUE THREAD

**Issue by jophy-ye** [datalayer/jupyter-ui#339]
## Description

<img width="988" alt="螢幕截圖 2024-12-17 下午5 19 01" src="https://github.com/user-attachments/assets/703c5170-149d-40f8-85a5-515a5fe07087" />

## Reproduce

1. Go to `/examples/next-js`
2. Do a clean install: `yarn install`
3. Run dev server: `yarn dev`

## Expected behavior

It's kind of awkward that the default example is falling apart? Should I explicitly install some other packages?

## Context

- Datalayer version: 0.19.1 (latest) of @datalayer/jupyter-react
- Operating System and version: MacOS 13.3.1 (a), M2
- Browser and version: x

**Comment by echarles** [comment]
Thx you @jophy-ye for reporting this. I have opened https://github.com/datalayer/jupyter-ui/pull/340 that should be merged soon.

**Comment by jophy-ye** [comment]
@echarles I'm getting started on the project so unfortunately I cannot help with these issues at the moment. Thanks for fixing.

**Comment by echarles** [comment]
@jophy-ye Please keep on reporting any issue or feature request. That is super useful :+1: 

The PR is merged, the examples are now operational again.
