### ISSUE TITLE
Add type for `injectableStore`

### ISSUE THREAD

**Issue by peytondmurray** [datalayer/jupyter-ui#36]
### Problem

The `JupyterContextType` contains an `injectableStore` entry, which is the redux store for the `jupyter-react`. The type of `injectableStore` is currently `any`, which bypasses static type checking and triggers errors when linted with tslint:

- `@typescript-eslint/no-unsafe-assignment`: If you use object destructuring on the `useJupyter` hook to access `injectableStore`
- `@typescript-eslint/no-unsafe-member-access`: If you try to call `injectableStore.dispatch()`
- `@typescript-eslint/no-unsafe-call`: If you try to call `injectableStore.dispatch()`
 

### Proposed Solution

- Add a type to the `injectableStore`. In `Store.ts`, could we have

```typescript
export type AppStore = typeof injectableStore;
```

?

**Comment by echarles** [comment]
To avoid users of this library to have to import a lot of jupyterlab packages while initialising the Redux store, a injectable store has been implemented to allow to lazy construct that Redux store. If we type injectableStore, the initial bundle will have to pull a lot of jupyterlab packages, which will weight a lot in the initial application loading.

We can think on how to tackle that to give a better experience, so let's leave this issue open for further discussion.

**Comment by echarles** [comment]
injectableStore is now typed as `InjectableStore`, done in https://github.com/datalayer/jupyter-ui/commit/469dfe7ec60b9d63bd040201542507efa6f4ff4b#diff-8fbf114973d6ded92d50de4776da769a050b603b19bd3a5d463f2f8276356dee

Closing. Thx @peytondmurray
