### ISSUE TITLE
Replace material-ui with primer

### ISSUE THREAD

**Issue by echarles** [datalayer/jupyter-ui#54]

**Comment by echarles** [comment]
@dbhagesh I have just pushed a few changes after the merge of https://github.com/datalayer/jupyter-ui/pull/56

The CRA example is now showing the Gallery. A few fixes are needed as show in the below image

1. The toolbar should be a real toolbar. Therefor, the actions buttons could be wrapped into a Primer IconButton (https://primer.style/react/IconButton - https://primer.style/react/storybook/?path=/story/components-iconbutton-features--danger) - The layout can be done with simple `Box`.(not sure if a full Header https://primer.style/react/Header is suited).

2. The CellSidebar has 2 issues: (a) While hovering on top with the mouse, the mouse does not show as clickable (b) Adding a cell add the sidebars, it should remove it, there is probably a need to check the previous logic that was working fine for the MUI CellSidebar as show here https://github.com/datalayer/jupyter-ui/blob/6aa2b33cc716db7119e02a364716cc57951eeb1e/examples/cra/src/examples/notebook/CellSidebarComponent.tsx#L20-L26

![Untitled6](https://user-images.githubusercontent.com/226720/236779539-b1a0ac1c-90f6-47ed-b264-910324c4b9f3.gif)

**Comment by echarles** [comment]
@dbhagesh I have pushed a fix for the multiple sidebar display. This is working fine now.

The list of actions of the sidebar should be update to reflect the previous mui list (also the space between the items and the mouse hover should be fixed).

Was

<img width="122" alt="Screenshot 2023-05-08 at 11 55 41" src="https://user-images.githubusercontent.com/226720/236797071-5ec53009-0fc7-463e-926e-906914b90593.png">

Is now (should be updated to reflect the previous display)

<img width="133" alt="Screenshot 2023-05-08 at 12 07 13" src="https://user-images.githubusercontent.com/226720/236797151-a5be3510-c117-4136-90b8-e8759c71ad74.png">

**Comment by dbhagesh** [comment]
Created a PR for /packages/react changes.
[https://github.com/datalayer/jupyter-ui/pull/57](url)

**Comment by echarles** [comment]
Done.
