### ISSUE TITLE
Ensure the Cell toolbar is visible

### ISSUE THREAD

**Issue by echarles** [datalayer/jupyter-ui#73]
https://github.com/datalayer/jupyter-ui/issues/68#issuecomment-1579216341 reports issues with the Cell toolbar which is not visible.

Running a Cell example from this repository shows the toolbar with the buttons being SVG loaded from CSS via https://github.com/datalayer/jupyter-ui/blob/77239db3a31cb998af7bf7c129331ae53472e76a/packages/react/webpack.config.js#L133-L141

<img width="688" alt="Screenshot 2023-06-07 at 08 32 39" src="https://github.com/datalayer/jupyter-ui/assets/226720/2f4e20fb-705e-45a4-8fde-653e77e88bc3">

However, the codesandbox CRA example https://codesandbox.io/p/sandbox/jupyter-react-cra-example-forked-l6jivn does not show the toolbar as the needed Webpack rules are not present by default in CRA.

**Comment by echarles** [comment]
@jaydeanmartin if webpack can not be configured in you app, you can create your own react.js toolbar. This is anyway how you want to do in a real case situation to trigger any action from your custom toolbar.

**Comment by jaydeanmartin** [comment]
I completely agree about creating custom toolbars. I am looking for simple solutions for prototyping capabilities.
I am not sure how I might go about adding the webpack rule at this point. I am installing everything in a docker container and things are being built on the fly. I will need to think about it some more.
Thank you for your response.

**Comment by echarles** [comment]
Closing as the issue is related to a webpack config.

@jaydeanmartin  Please reopen or open a new one if you are still facing issue. Thx again!
