### ISSUE TITLE
Support VSCode Devcontainer

### ISSUE THREAD

**Issue by echarles** [datalayer/jupyter-ui#75]
See [this documentation](https://code.visualstudio.com/docs/devcontainers/containers). The devcontainer would have the needed Conda and Jupyter environment.

**Comment by jaydeanmartin** [comment]
I currently develop in WSL and connect VSCode to that (from Windows host). From WSL I spin up containers for the Jupyter server (jupyter-stacks based container can be used) and for the "frontend" React files (node.js-based container). In a development environment, node.js will auto build and serve files it sees changed. A directory (volume) containing src and public directories is shared with the host operating system, in this case WSL. As files are edited and saved with VSCode, they will automatically "appear" in your web-browser.
