### ISSUE TITLE
Fail to setup the environment

### ISSUE THREAD

**Issue by imerlwx** [datalayer/jupyter-ui#77]
When I run "yarn build", it failed with the following issue:
 Lerna (powered by Nx)   Ran target build for 19 projects (14s)
 
    ✔    10/12 succeeded [0 read from cache]
 
    ✖    2/12 targets failed, including the following:
         - @datalayer/jupyter-react:build
         - @datalayer/jupyter-esbuild-example:build

I have tried both the container and conda, neither works. How to solve this?

**Comment by echarles** [comment]
Thx for reporting. Some 3rd party libs were not released. Could you pull the latest change and try again. I will work on https://github.com/datalayer/jupyter-ui/issues/65 to ensure more stability for the build.

**Comment by imerlwx** [comment]
Thank you! Now, most of the projects can be built but still:
 Lerna (powered by Nx)   Ran target build for 18 projects (33m)
 
    ✔    15/16 succeeded [0 read from cache]
 
    ✖    1/16 targets failed, including the following:
         - @datalayer/jupyter-lexical:build

**Comment by echarles** [comment]
Can you share the details of the error? If you are interested in just the react part, you can cd to packages/react and run yarn build from there.

**Comment by imerlwx** [comment]
Thanks for your help, the build is successful now.
