### ISSUE TITLE
Injectable Store Tutorial

### ISSUE THREAD

**Issue by MukkundB** [datalayer/jupyter-ui#79]
### Problem

I am trying to use `jupyter-ui` to build a new front-end client as opposed to the regular jupyter notebook. 

In the process, I have found the need to use the redux store initialised in the `jupyter-ui` library. I see that there is a brief mention of an [injectable store](https://jupyter-ui.datalayer.tech/docs/components/context/) in the documentation. However, I cannot find any further information. 

After digging through the code-base, I did find a, now-deprecated example with [es-build](https://github.com/datalayer/jupyter-ui/blob/main/attic/esbuild/src/state/store.ts). I still find quite some issues trying to inject my redux store. 

### Ask

Is there any piece of documentation or an example that shows the usage of the prop `injectableStore` in the `Jupyter` component? Any direction or advise on this would be highly appreciated.

**Comment by echarles** [comment]
Hi @MukkundB I will try to document the injectable store and create an example for that.

BTW We are considering to add Mobx to Redux (or replace it?). Could you give any thoughts on that, and maybe describe your use case to see if Mobx could do the job for you also?

**Comment by Bshara23** [comment]
Would like to also add a suggestion, [zustand](https://github.com/pmndrs/zustand) is very popular choice for state management, it could be relevant for a lot of people;
A simple example or doc on how to inject it would be very helpful

**Comment by echarles** [comment]
@MukkundB I have added a section about state in the doc https://jupyter-ui.datalayer.tech/docs/state/redux which points to an example I have just pushed. The example show how to create you own state/action/reducer, enroll it in jupyter-react, and use it. Looking forward to your feedback.

**Comment by echarles** [comment]
> Would like to also add a suggestion, [zustand](https://github.com/pmndrs/zustand) is very popular choice for state management, it could be relevant for a lot of people;

@Bshara23 We can continue the discussion on redux/mobx/zustand on https://github.com/datalayer/jupyter-ui/issues/50

**Comment by MukkundB** [comment]
@echarles Thanks a lot for adding an example in the repo. 

As far as the state management, I do not necessarily have an opinion. 

I am trying to build a alternative UI for Jupyter notebooks. Since there is a heavy dependence to JupyterUI, I believe I will be using the same state management library as the one used here to simplify things. 

In any case, for the sake of building a simple prototype, using a redux store would do.

**Comment by echarles** [comment]
Closing as resolved. Please open a new issues if you need more help.
