### ISSUE TITLE
Jupyter Notebook not working

### ISSUE THREAD

**Issue by BrandonEscamilla** [datalayer/jupyter-ui#84]
## Description

The Notebook component of the Jupyter-UI library is not functioning properly in my Next.js application. Specifically, it fails to load and display on the webpage. Although the kernel successfully loads and connects, the Notebook component itself does not appear. However, I have discovered that when I include a Cell component before the Notebook component, it starts to work as expected. Therefore, it seems that using the Cell component alongside the Notebook component resolves the issue.

## Reproduce

To reproduce the issue, follow these steps:
	1.	Set up a Next.js application example.
	2.	Import Notebook component.
	3.	Add a Notebook component without a preceding Cell component.
	4.	Run the application and observe that the Notebook component fails to load.
	5.	Add a Cell component before the Notebook component.
	6.	Run the application again and observe that both the Cell and Notebook components now load correctly.

## Expected Behavior

I expected the Notebook component to load without using Cell component.

## Context
Please provide the following information for better context:
	•	Datalayer version: ^0.5.1
	•	Operating System and version: macOS, Ventura 13.0.1
	•	Browser and version: Arc, Version 1.2.1 (40552)

## Browser Output
![CleanShot 2023-08-08 at 14 54 33](https://github.com/datalayer/jupyter-ui/assets/21966716/2e4af0b4-ca0f-4613-9769-020a1bf5e6bc)

**Comment by echarles** [comment]
The notebook was well in the DOM tree but "some" CSS rules were hiding it on my env.

I have create a new page.tsx with just the Notebook and it works fine https://github.com/datalayer/jupyter-ui/blob/d2aaa88d572204cc7c5ce6e5952d4997f88f11ae/examples/next-js/src/app/page.tsx

The log you show are warning, not ideal, should be fixed later.

**Comment by BrandonEscamilla** [comment]
Yes, it appears that the Notebook component is not being displayed when it is wrapped within the main ﻿<div> of my Next.js application. I believe we can consider this particular issue closed. Thank you so much for your time and assistance, @echarles. I truly appreciate your help!

**Comment by echarles** [comment]
Closing as answered.
