### ISSUE TITLE
model is null

### ISSUE THREAD

**Issue by rrickyp** [datalayer/jupyter-ui#87]
I have already followed your instruction in https://github.com/datalayer/jupyter-ui/issues/86#issuecomment-1672783193. The code works, however, there are 2 errors that come out
```
Unhandled Runtime Error
TypeError: model is null
Call Stack
execute
node_modules/@jupyterlab/cells/lib/widget.js (1160:0)
Cell/</<
node_modules/@datalayer/jupyter-react/lib/components/cell/Cell.js (35:36)
```
and
```
Unhandled Runtime Error

TypeError: _this._codeCell.model is null
Call Stack
CellAdapter/</<
node_modules/@datalayer/jupyter-react/lib/components/cell/CellAdapter.js (124:16)
```
I tried using npm and yarn, but both of them still produce those 2 errors. 
Can you help me to solve this, I have edited the code in the github? Thanks in advance

**Comment by echarles** [comment]
@rrickyp Can you confirm you have pushed everything in https://github.com/rrickyp/jupyter_test - Then I can have a look. thx.

**Comment by rrickyp** [comment]
> @rrickyp Can you confirm you have pushed everything in https://github.com/rrickyp/jupyter_test - Then I can have a look. thx.

Yes, I have already pushed it. Just to let you know, the website still works despite of the error. Thanks

**Comment by echarles** [comment]
@rrickyp This then we have fixed a lot of issues (with the help of @BrandonEscamilla) for the next.js case which is working fine now.

- See doc on https://jupyter-ui.datalayer.tech/docs/examples/next-js
- See example repo on https://github.com/datalayer-examples/jupyter-nextjs-example

I will close this issue, just open an new one for any question or problem. Thx again!

**Comment by echarles** [comment]
PS: See also live version on https://jupyter-nextjs-example.vercel.app/
