### ISSUE TITLE
path is going to https://oss.datalayer.tech/api/jupyter/api/contents/...

### ISSUE THREAD

**Issue by rrickyp** [datalayer/jupyter-ui#89]
hi i was planning to add the existing .ipynb file to path with url
      `<Notebook path="some_url" ipywidgets="classic"/>`
but it goes to this url https://oss.datalayer.tech/api/jupyter/api/contents/some_url.
Thank you in advance.

**Comment by echarles** [comment]
If you are looking to load a file from your own server, please have a look at https://jupyter-ui.datalayer.tech/docs/deployments/jupyter-server/

**Comment by echarles** [comment]
@rrickyp Have you solved your issue?

**Comment by rrickyp** [comment]
yes, thank you so much!

**Comment by echarles** [comment]
Thx. Closing.
