### ISSUE TITLE
Help with Redux implementation

### ISSUE THREAD

**Issue by BrandonEscamilla** [datalayer/jupyter-ui#91]
Hi everyone, 

I am seeking assistance on how to properly implement the Redux ﻿injectableStore in my project as it is not functioning as expected. Here is what I have done so far: I created a store using Redux Toolkit and set up the provider in ﻿layout.tsx (next.js 13, using app dir), passing the store as a prop. 

```jsx 
// layout.jsx
<Provider store={store}
  {children}
</Provider>

```

Next, I proceeded to create the injectable store by following these steps:

```jsx
// Importing store
import store from '../store';
...

export default Home() {
// Create injectableStore
const dispatch = useDispatch()
const injectableStore = createInjectableStore(store);
....

// Using InjectableStore
<Jupyter          
     injectableStore={injectableStore}
.....
```

By implementing the injectable store, I expect to use the actions like this: 

```jsx
<Jupyter          
     injectableStore={injectableStore}
....
<Button onClick={e => { e.preventDefault(); 
    dispatch(
     notebookActions.insertAbove.started({
      uid: NOTEBOOK_UID,
      cellType: 'code',
    }));
}}>Insert</Button>
....
```
After implementing the injectable store, the Notebook toolbar stopped working. dispatch() doesn't seems to work (screenshot below with the errors in console). I am pretty sure I am doing something wrong. Any thoughts on this issue? Thank you in advance for your help.

![CleanShot 2023-08-18 at 12 20 47](https://github.com/datalayer/jupyter-ui/assets/21966716/9c463f86-7d0f-4844-8a63-a1a52dc9c0f0)

**Comment by echarles** [comment]
This has been discuss in https://github.com/datalayer/jupyter-ui/issues/79 and resulted with a example you can link from https://jupyter-ui.datalayer.tech/docs/state/redux/

**Comment by echarles** [comment]
@BrandonEscamilla Maybe you have already seen that example, please tell me if it help or not, so I can look a bit more to the code you shared.

**Comment by BrandonEscamilla** [comment]
Hey @echarles, thank you for you answer, in fact, I did check out the resource you shared. But I'm a bit confused about whether I need to set up the store like we usually do in Redux, or is simply creating the store with const store = createReduxEpicStore(); enough? Also, I'm not sure if I have to worry about this part: injectableStore.inject('init', exampleReducer);. Any insights you could give me on this? 
Appreciate your help!

**Comment by echarles** [comment]
> const store = createReduxEpicStore(); enough? Also, I'm not sure if I have to worry about this part: 

It should be enough

> injectableStore.inject('init', exampleReducer);. Any insights you could give me on this?

the easiest if to start from the ExampleState file and change it to fit your needs. There may be other constructs to integrate Redux, but that example is the easiest I have found. You could copy/paste it and change it to your needs.

**Comment by BrandonEscamilla** [comment]
Hi @echarles, I'm currently encountering some challenges while trying to implement this. Could you please suggest any alternative resources or references that I can explore? Thank you in advance!

**Comment by echarles** [comment]
Just sent an invite to connect on linkedin and schedule a call. Is your repo public so I can already have a look?

**Comment by BrandonEscamilla** [comment]
Hi @echarles, fortunately, I just managed to make it work. Thank you for suggesting the meeting; your support is greatly appreciated.

**Comment by echarles** [comment]
That is awesome news. At some point, this community will benefit from your knowledge if this can be published in the open.

Anyway I let you share here what is possible, and let you close it after. Thx again.

**Comment by BrandonEscamilla** [comment]
Hey @echarles, thanks for the support. I managed to solve the issue by creating the store using the `createReduxEpicStore()` function provided by jupyter-ui, before I was creating the store using redux-toolkit but it was not working. In Next.js, I simply created the store using that function and passed it to the Redux provider. To access the store in the page where I'm using Jupyter notebooks, I used the `useStore()` selector. The example reducer is just a copy-paste of the one in the repo as well. Here's the code:


```jsx 
//layout.tsx

import { Provider } from "react-redux";
import { createReduxEpicStore } from "@datalayer/jupyter-react";

const store = createReduxEpicStore()
<Provider store={store}>
    {children}
</Provider>
```

```jsx
//page.tsx
import { exampleReducer } from '@/redux/ExampleState';
import { Jupyter, notebookActions, createInjectableStore } from '@datalayer/jupyter-react';

const store = useStore()
const injectableStore = createInjectableStore(store);    
injectableStore.inject('init', exampleReducer);

<Jupyter
   injectableStore={injectableStore}
   .....
 >
```


```jsx
// ExampleState.ts

import { useSelector } from "react-redux";
import actionCreatorFactory from "typescript-fsa";
import { reducerWithInitialState } from "typescript-fsa-reducers";
import { IJupyterReactState } from "@datalayer/jupyter-react";

/* State */

export interface IExampleState {
  foo?: Date;
}

export const initExampleState: IExampleState = {
  foo: undefined,
}

/* Selectors */

export const selectFoo = (): Date | undefined =>
  useSelector((state: IJupyterReactState) => {
    if (state.init) {
      return (state.init as IExampleState).foo;
    }
    return initExampleState.foo;
  }
);

/* Actions */

export enum ExampleActionType {
  UPDATE_FOO = "jupyterReact/UPDATE_FOO",
}

const actionCreator = actionCreatorFactory('jupyterReact');

export const exampleActions = {
  updateFoo: actionCreator<Date>(
    ExampleActionType.UPDATE_FOO
  ),
}

/* Reducers */

export const exampleReducer = reducerWithInitialState(initExampleState)
  .case(exampleActions.updateFoo, (state: IExampleState, foo: Date) => {
    return {
      ...state,
      foo,
    };
  }
);
```

**Comment by echarles** [comment]
Super! Thx for sharing. Closing as resolved.
