### ISSUE TITLE
Example for how to set the initial cell value

### ISSUE THREAD

**Issue by xMort** [datalayer/jupyter-ui#95]
### Problem
I know that I can add new cell by dispatching the following action

 `injectableStore.dispatch(notebookActions.insertAbove.started({ uid: notebookId, cellType: "code" }));`

However, can I somehow set it's initial value? For example put there imports to some packages, etc.?

### Solution

Something like 
 `injectableStore.dispatch(notebookActions.insertAbove.started({ uid: notebookId, cellType: "code", value: "from setup import *" }));`

**Comment by echarles** [comment]
That would be a great feature. I have prioritized this issue for me  (3rd place for now in my pipeline). The first one is really annonying (kernel related), and the second one is a long standing one. Otherwise feel free to jump in to the code if you feel like and have time for, and ask question to find your way.

<img width="1251" alt="Screenshot 2023-08-31 at 05 16 32" src="https://github.com/datalayer/jupyter-ui/assets/226720/d0098c33-e450-4732-9cd1-bbf75cd7b453">

**Comment by xMort** [comment]
Thank you for looking into it. I will continue finding the way and will update the issue if I will come up with something.

**Comment by echarles** [comment]
> I will continue finding the way and will update the issue if I will come up with something.

Cool! While fixing stuff, I have quickly implemented this feature. It works on my laptop and will be released tomorrow.
This API is `started({ uid: notebookId, cellType: "code", source: "from setup import *" }));`

![Untitled6](https://github.com/datalayer/jupyter-ui/assets/226720/6c3ab7dd-9968-41b1-9e72-6ed95dcf36c7)

**Comment by xMort** [comment]
> Cool! While fixing stuff, I have quickly implemented this feature.

WOW, that was quick! I have no words. Thank you

**Comment by echarles** [comment]
Just release 0.7.0. You can try based on that example https://github.com/datalayer/jupyter-ui/blob/092b1fe5c17b655e79ea163efcb797a0ff323883/packages/react/src/examples/sidebars/CellSidebarSource.tsx

Please close this issue if it works for you.

**Comment by echarles** [comment]
@xMort I will it this now, it is hopefully fine for you. Reopen of open a new one for anything. Thx again!

**Comment by xMort** [comment]
I will test it on Monday and let you know. Thank you so much for the new release.

**Comment by echarles** [comment]
The last one is 0.7.4 has much better next.js support in case you need it.

**Comment by xMort** [comment]
@echarles I tried the new release and it works as expected 🎉
Once again, thank you for your quick response!
