### ISSUE TITLE
How to programatically find out that notebook is ready?

### ISSUE THREAD

**Issue by xMort** [datalayer/jupyter-ui#98]
### Problem

I'm loading a notebook via `<Notebook path="/notebook.ipynb" />`.
 
When it is loaded, I want to dispatch events to replace it first cell via `injectableStore.dispatch(notebookActions.delete.started(uid));` and then after small timeout by `injectableStore.dispatch(notebookActions.insertAbove.started( ... ));` The timeout is there because I can't determine when the first event finished and state was updated.

The reason for this sequence of actions is that the first notebook cell contains some variables necessary to run the whole notebook. I want to customize these variables based on the application context. Maybe there is a better way how to customize the loaded notebook dynamically?

Generally, my problem is that I can't find out reliable way how to determine when notebook is loaded and I can fire the first actions from sequence above. I tried various selectors, listening to store events, etc. but I can't find the documentation for most of the selectors or for the notebook state model. I'm listening to some store events and then I'm using timeouts which is highly suboptimal and it fails from time to time as I fire the event sooner than I should.

Can you help me to understand when I can fire my first event and how do I determine that async action finished? 

Thank you

### Suggested Improvement

* Documentation showing how to determine that notebook finished loading and actions modifying it can be dispatched.
* Documentation showing how to work with async dispatch actions.

**Comment by echarles** [comment]
> Generally, my problem is that I can't find out reliable way how to determine when notebook is loaded 

Question: What is your definition of "loaded"?

- The ipynb is fetched from the server?
- The visual notebook is shown to the user?
- The notebook associated kernel is available and ready to run code?
- Something else?

**Comment by xMort** [comment]
@echarles I made this simplified example of my code to illustrate what I'm trying to do.

I don't want to have timeout in the effect below and want to know when I can safely dispatch the notebook modification action. If there is no timeout, the action have no effect (probably because notebook get rendered after the effect is called due to condition that waits for new kernel).

````
import React, { useEffect, useState, useRef } from "react";
import {
    CellSidebar,
    IJupyterReactState,
    Jupyter,
    Kernel,
    Notebook,
    createInjectableStore,
    createReduxEpicStore,
    useJupyter, notebookActions
} from "@datalayer/jupyter-react";
import NotebookToolbar from "@datalayer/jupyter-react/lib/examples/toolbars/NotebookToolbar";

// my configuration of jupyter server integration
import {
    JUPYTER_KERNEL_NAME,
    JUPYTER_REST_API_URL,
    JUPYTER_TOKEN,
    JUPYTER_WS_URL,
} from "./JupyterConfiguration";

const NOTEBOOK_ID = "notebook";
const NOTEBOOK_WIDTH = 500;
const NOTEBOOK_HEIGHT = 500;

const jupyterStore = createReduxEpicStore();
const injectableStore = createInjectableStore(jupyterStore);

injectableStore.inject("init", (state: IJupyterReactState, _action: any) => {
    return state || {};
});

const useKernel = () => {
    const { kernelManager, serverSettings } = useJupyter();
    const [kernel, setKernel] = useState<Kernel>();

    // create notebook kernel
    useEffect(() => {
        let startedKernel: Kernel;

        kernelManager?.ready.then(() => {
            const customKernel = new Kernel({
                kernelManager,
                serverSettings,
                kernelSpecName: JUPYTER_KERNEL_NAME,
                kernelName: JUPYTER_KERNEL_NAME,
                kernelType: "notebook",
            });
            customKernel.ready.then(() => {
                startedKernel = customKernel;
                setKernel(customKernel);
            });
        });
        return () => {
            if (startedKernel) {
                kernelManager?.shutdown(startedKernel.id).then();
            }
        };
    }, [kernelManager, serverSettings]);

    return kernel;
};

const ActualNotebook: React.FC = () => {
    const kernel = useKernel();
    const initialized = useRef(false);

    useEffect(() => {
      if(kernel && !initialized.current) {
          initialized.current = true;

          // this cell will not get injected unless there is some timeout
          // how to determine when it is safe to dispatch this action? 
          setTimeout(() => {
              injectableStore.dispatch(
                notebookActions.insertAbove.started({
                    uid: NOTEBOOK_ID,
                    cellType: "code",
                    source: `from utils import *`,
                }),
              );
          }, 2000);
      }
    }, [kernel]);

    return (
        kernel && (
            <Notebook
                kernel={kernel}
                height={`calc(${NOTEBOOK_HEIGHT}px - 2.6rem)`}
                CellSidebar={CellSidebar}
                Toolbar={NotebookToolbar}
                path="/forecast.ipynb"
                uid={NOTEBOOK_ID}
            />
        )
    );
};

// Component used somewhere in the app to inject notebook
export const EmbeddedNotebook: React.FC = () => {
    return (
        <Jupyter
            startDefaultKernel={false}
            injectableStore={injectableStore}
            jupyterServerHttpUrl={JUPYTER_REST_API_URL}
            jupyterServerWsUrl={JUPYTER_WS_URL}
            jupyterToken={JUPYTER_TOKEN}
        >
            <div style={{width: NOTEBOOK_WIDTH, height: NOTEBOOK_HEIGHT}}>
                <ActualNotebook />
            </div>
        </Jupyter>
    );
};
````

**Comment by echarles** [comment]
This was a bit tricky, the condition is not the kernel but the content. See this example https://github.com/datalayer/jupyter-ui/blob/main/packages/react/src/examples/NotebookInit.tsx

**Comment by echarles** [comment]
I guess we could have a better api that would indicate that the notebook content is loaded with a promise.

**Comment by xMort** [comment]
@echarles it works, thank you so much for the quick example ❤️
